/**
 * Sample Vocabulary Data
 *
 * Comprehensive vocabulary for testing the flashcard system.
 * Organized by category and difficulty level.
 */

import { Flashcard, FlashcardCategory, DifficultyLevel } from '@/types/flashcard';

type SampleFlashcard = Omit<Flashcard, 'id' | 'created_at' | 'updated_at'>;

/**
 * Food & Dining vocabulary
 */
export const foodVocabulary: SampleFlashcard[] = [
  {
    word: 'apple',
    translation: 'manzana',
    phonetic: '/ˈæp.əl/',
    category: 'food',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I eat an apple every day.',
    example_translation: 'Como una manzana todos los días.',
  },
  {
    word: 'water',
    translation: 'agua',
    phonetic: '/ˈwɔː.tər/',
    category: 'food',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Can I have some water, please?',
    example_translation: '¿Puedo tener un poco de agua, por favor?',
  },
  {
    word: 'bread',
    translation: 'pan',
    phonetic: '/bred/',
    category: 'food',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I love fresh bread.',
    example_translation: 'Me encanta el pan fresco.',
  },
  {
    word: 'coffee',
    translation: 'café',
    phonetic: '/ˈkɔː.fi/',
    category: 'food',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I drink coffee in the morning.',
    example_translation: 'Tomo café por la mañana.',
  },
  {
    word: 'chicken',
    translation: 'pollo',
    phonetic: '/ˈtʃɪk.ɪn/',
    category: 'food',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'The chicken is delicious.',
    example_translation: 'El pollo está delicioso.',
  },
  {
    word: 'rice',
    translation: 'arroz',
    phonetic: '/raɪs/',
    category: 'food',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'We eat rice with vegetables.',
    example_translation: 'Comemos arroz con verduras.',
  },
  {
    word: 'milk',
    translation: 'leche',
    phonetic: '/mɪlk/',
    category: 'food',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Do you want milk with your cereal?',
    example_translation: '¿Quieres leche con tu cereal?',
  },
  {
    word: 'cheese',
    translation: 'queso',
    phonetic: '/tʃiːz/',
    category: 'food',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I like cheese on my sandwich.',
    example_translation: 'Me gusta el queso en mi sándwich.',
  },
  {
    word: 'egg',
    translation: 'huevo',
    phonetic: '/eɡ/',
    category: 'food',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I had two eggs for breakfast.',
    example_translation: 'Comí dos huevos en el desayuno.',
  },
  {
    word: 'vegetable',
    translation: 'verdura/vegetal',
    phonetic: '/ˈvedʒ.tə.bəl/',
    category: 'food',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Eat your vegetables!',
    example_translation: '¡Come tus verduras!',
  },
  {
    word: 'fruit',
    translation: 'fruta',
    phonetic: '/fruːt/',
    category: 'food',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Fresh fruit is healthy.',
    example_translation: 'La fruta fresca es saludable.',
  },
  {
    word: 'soup',
    translation: 'sopa',
    phonetic: '/suːp/',
    category: 'food',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'This soup is hot.',
    example_translation: 'Esta sopa está caliente.',
  },
  {
    word: 'salad',
    translation: 'ensalada',
    phonetic: '/ˈsæl.əd/',
    category: 'food',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I want a green salad.',
    example_translation: 'Quiero una ensalada verde.',
  },
  {
    word: 'fish',
    translation: 'pescado',
    phonetic: '/fɪʃ/',
    category: 'food',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'We eat fish on Fridays.',
    example_translation: 'Comemos pescado los viernes.',
  },
  {
    word: 'juice',
    translation: 'jugo/zumo',
    phonetic: '/dʒuːs/',
    category: 'food',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Orange juice is my favorite.',
    example_translation: 'El jugo de naranja es mi favorito.',
  },
];

/**
 * Travel Essentials vocabulary
 */
export const travelVocabulary: SampleFlashcard[] = [
  {
    word: 'airport',
    translation: 'aeropuerto',
    phonetic: '/ˈer.pɔːrt/',
    category: 'travel',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'The airport is very busy.',
    example_translation: 'El aeropuerto está muy ocupado.',
  },
  {
    word: 'hotel',
    translation: 'hotel',
    phonetic: '/hoʊˈtel/',
    category: 'travel',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Where is the hotel?',
    example_translation: '¿Dónde está el hotel?',
  },
  {
    word: 'ticket',
    translation: 'boleto/billete',
    phonetic: '/ˈtɪk.ɪt/',
    category: 'travel',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I need a ticket to New York.',
    example_translation: 'Necesito un boleto a Nueva York.',
  },
  {
    word: 'passport',
    translation: 'pasaporte',
    phonetic: '/ˈpæs.pɔːrt/',
    category: 'travel',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Show me your passport, please.',
    example_translation: 'Muéstreme su pasaporte, por favor.',
  },
  {
    word: 'taxi',
    translation: 'taxi',
    phonetic: '/ˈtæk.si/',
    category: 'travel',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Can you call a taxi?',
    example_translation: '¿Puedes llamar un taxi?',
  },
  {
    word: 'train',
    translation: 'tren',
    phonetic: '/treɪn/',
    category: 'travel',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'The train arrives at 3 PM.',
    example_translation: 'El tren llega a las 3 PM.',
  },
  {
    word: 'bus',
    translation: 'autobús',
    phonetic: '/bʌs/',
    category: 'travel',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Where is the bus stop?',
    example_translation: '¿Dónde está la parada de autobús?',
  },
  {
    word: 'map',
    translation: 'mapa',
    phonetic: '/mæp/',
    category: 'travel',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I need a map of the city.',
    example_translation: 'Necesito un mapa de la ciudad.',
  },
  {
    word: 'suitcase',
    translation: 'maleta',
    phonetic: '/ˈsuːt.keɪs/',
    category: 'travel',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'My suitcase is heavy.',
    example_translation: 'Mi maleta está pesada.',
  },
  {
    word: 'luggage',
    translation: 'equipaje',
    phonetic: '/ˈlʌɡ.ɪdʒ/',
    category: 'travel',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Where is my luggage?',
    example_translation: '¿Dónde está mi equipaje?',
  },
  {
    word: 'reservation',
    translation: 'reserva/reservación',
    phonetic: '/ˌrez.ərˈveɪ.ʃən/',
    category: 'travel',
    difficulty: 'intermediate',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I have a reservation under Smith.',
    example_translation: 'Tengo una reserva a nombre de Smith.',
  },
  {
    word: 'flight',
    translation: 'vuelo',
    phonetic: '/flaɪt/',
    category: 'travel',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'What time is the flight?',
    example_translation: '¿A qué hora es el vuelo?',
  },
  {
    word: 'station',
    translation: 'estación',
    phonetic: '/ˈsteɪ.ʃən/',
    category: 'travel',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'The train station is nearby.',
    example_translation: 'La estación de tren está cerca.',
  },
  {
    word: 'beach',
    translation: 'playa',
    phonetic: '/biːtʃ/',
    category: 'travel',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Let\'s go to the beach!',
    example_translation: '¡Vamos a la playa!',
  },
  {
    word: 'museum',
    translation: 'museo',
    phonetic: '/mjuːˈziː.əm/',
    category: 'travel',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'The museum is open today.',
    example_translation: 'El museo está abierto hoy.',
  },
];

/**
 * Common Verbs vocabulary
 */
export const verbsVocabulary: SampleFlashcard[] = [
  {
    word: 'to be',
    translation: 'ser/estar',
    phonetic: '/tuː biː/',
    category: 'verbs',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I am happy.',
    example_translation: 'Estoy feliz.',
  },
  {
    word: 'to have',
    translation: 'tener',
    phonetic: '/tuː hæv/',
    category: 'verbs',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I have a car.',
    example_translation: 'Tengo un carro.',
  },
  {
    word: 'to go',
    translation: 'ir',
    phonetic: '/tuː ɡoʊ/',
    category: 'verbs',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I go to work every day.',
    example_translation: 'Voy al trabajo todos los días.',
  },
  {
    word: 'to eat',
    translation: 'comer',
    phonetic: '/tuː iːt/',
    category: 'verbs',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'We eat dinner at 7 PM.',
    example_translation: 'Cenamos a las 7 PM.',
  },
  {
    word: 'to drink',
    translation: 'beber/tomar',
    phonetic: '/tuː drɪŋk/',
    category: 'verbs',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I drink water.',
    example_translation: 'Bebo agua.',
  },
  {
    word: 'to speak',
    translation: 'hablar',
    phonetic: '/tuː spiːk/',
    category: 'verbs',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Do you speak English?',
    example_translation: '¿Hablas inglés?',
  },
  {
    word: 'to want',
    translation: 'querer',
    phonetic: '/tuː wɑːnt/',
    category: 'verbs',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I want to learn.',
    example_translation: 'Quiero aprender.',
  },
  {
    word: 'to need',
    translation: 'necesitar',
    phonetic: '/tuː niːd/',
    category: 'verbs',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I need help.',
    example_translation: 'Necesito ayuda.',
  },
  {
    word: 'to like',
    translation: 'gustar',
    phonetic: '/tuː laɪk/',
    category: 'verbs',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I like pizza.',
    example_translation: 'Me gusta la pizza.',
  },
  {
    word: 'to know',
    translation: 'saber/conocer',
    phonetic: '/tuː noʊ/',
    category: 'verbs',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I know the answer.',
    example_translation: 'Sé la respuesta.',
  },
];

/**
 * Everyday Objects vocabulary
 */
export const objectsVocabulary: SampleFlashcard[] = [
  {
    word: 'phone',
    translation: 'teléfono',
    phonetic: '/foʊn/',
    category: 'objects',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Where is my phone?',
    example_translation: '¿Dónde está mi teléfono?',
  },
  {
    word: 'book',
    translation: 'libro',
    phonetic: '/bʊk/',
    category: 'objects',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I am reading a book.',
    example_translation: 'Estoy leyendo un libro.',
  },
  {
    word: 'pen',
    translation: 'bolígrafo/pluma',
    phonetic: '/pen/',
    category: 'objects',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Can I borrow your pen?',
    example_translation: '¿Puedo pedir prestado tu bolígrafo?',
  },
  {
    word: 'table',
    translation: 'mesa',
    phonetic: '/ˈteɪ.bəl/',
    category: 'objects',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'The keys are on the table.',
    example_translation: 'Las llaves están en la mesa.',
  },
  {
    word: 'chair',
    translation: 'silla',
    phonetic: '/tʃer/',
    category: 'objects',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Please sit on the chair.',
    example_translation: 'Por favor siéntate en la silla.',
  },
  {
    word: 'door',
    translation: 'puerta',
    phonetic: '/dɔːr/',
    category: 'objects',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Close the door, please.',
    example_translation: 'Cierra la puerta, por favor.',
  },
  {
    word: 'window',
    translation: 'ventana',
    phonetic: '/ˈwɪn.doʊ/',
    category: 'objects',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'Open the window.',
    example_translation: 'Abre la ventana.',
  },
  {
    word: 'computer',
    translation: 'computadora/ordenador',
    phonetic: '/kəmˈpjuː.tər/',
    category: 'objects',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I work on my computer.',
    example_translation: 'Trabajo en mi computadora.',
  },
  {
    word: 'bag',
    translation: 'bolsa/bolso',
    phonetic: '/bæɡ/',
    category: 'objects',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'My bag is heavy.',
    example_translation: 'Mi bolsa está pesada.',
  },
  {
    word: 'key',
    translation: 'llave',
    phonetic: '/kiː/',
    category: 'objects',
    difficulty: 'beginner',
    target_language: 'en',
    native_language: 'es',
    example_sentence: 'I lost my keys.',
    example_translation: 'Perdí mis llaves.',
  },
];

/**
 * All vocabulary combined
 */
export const allVocabulary: SampleFlashcard[] = [
  ...foodVocabulary,
  ...travelVocabulary,
  ...verbsVocabulary,
  ...objectsVocabulary,
];

/**
 * Get vocabulary count by category
 */
export function getVocabularyStats() {
  return {
    food: foodVocabulary.length,
    travel: travelVocabulary.length,
    verbs: verbsVocabulary.length,
    objects: objectsVocabulary.length,
    total: allVocabulary.length,
  };
}
