import type { AddWordInput } from '@/lib/word-bank/types';

/**
 * 85 core English words for A1-A2 learners.
 * Covers greetings, essential verbs, daily life, time, polite phrases, and survival vocabulary.
 */
export const ENGLISH_BEGINNER: AddWordInput[] = [
  // ── Greetings & Introductions (10) ──────────────────────────────
  {
    word: 'Hello',
    translation: '(greeting)',
    phonetic: '/həˈloʊ/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Hello, how are you?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Goodbye',
    translation: '(farewell)',
    phonetic: '/ɡʊdˈbaɪ/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Goodbye, see you tomorrow!'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Please',
    translation: '(polite request)',
    phonetic: '/pliːz/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Please sit down.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Thank you',
    translation: '(gratitude)',
    phonetic: '/θæŋk juː/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Thank you for your help.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Yes',
    translation: '(affirmation)',
    phonetic: '/jɛs/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Yes, I understand.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'No',
    translation: '(negation)',
    phonetic: '/noʊ/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['No, thank you.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Good morning',
    translation: '(morning greeting)',
    phonetic: '/ɡʊd ˈmɔːrnɪŋ/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Good morning, everyone.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Good night',
    translation: '(night farewell)',
    phonetic: '/ɡʊd naɪt/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Good night, sleep well.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'My name is',
    translation: '(self-introduction)',
    phonetic: '/maɪ neɪm ɪz/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['My name is Ana.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Nice to meet you',
    translation: '(introduction response)',
    phonetic: '/naɪs tə miːt juː/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Nice to meet you, I am Carlos.'],
    milestoneTags: ['onboarding'],
  },

  // ── Common Questions (10) ───────────────────────────────────────
  {
    word: 'What',
    translation: '(question word)',
    phonetic: '/wɒt/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['What is your name?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Where',
    translation: '(place question)',
    phonetic: '/wɛr/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Where is the station?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'When',
    translation: '(time question)',
    phonetic: '/wɛn/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['When does the bus leave?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'How',
    translation: '(manner question)',
    phonetic: '/haʊ/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['How are you today?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Why',
    translation: '(reason question)',
    phonetic: '/waɪ/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Why is the shop closed?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Who',
    translation: '(person question)',
    phonetic: '/huː/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['Who is your teacher?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'How much',
    translation: '(price question)',
    phonetic: '/haʊ mʌtʃ/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['How much does this cost?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Do you speak English?',
    translation: '(language question)',
    phonetic: '/duː juː spiːk ˈɪŋɡlɪʃ/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Excuse me, do you speak English?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Can you help me?',
    translation: '(request for help)',
    phonetic: '/kæn juː hɛlp miː/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Can you help me find the hotel?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Which',
    translation: '(selection question)',
    phonetic: '/wɪtʃ/',
    category: 'question',
    cefrLevel: 'A2',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['Which one do you prefer?'],
    milestoneTags: ['onboarding'],
  },

  // ── Essential Verbs (15) ────────────────────────────────────────
  {
    word: 'Be',
    translation: '(existence/identity)',
    phonetic: '/biː/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['I am a student.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Have',
    translation: '(possession)',
    phonetic: '/hæv/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['I have two brothers.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Go',
    translation: '(movement)',
    phonetic: '/ɡoʊ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['I go to work every day.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Want',
    translation: '(desire)',
    phonetic: '/wɒnt/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['I want a glass of water.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Need',
    translation: '(necessity)',
    phonetic: '/niːd/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['I need to see a doctor.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Like',
    translation: '(preference)',
    phonetic: '/laɪk/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['I like coffee in the morning.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Know',
    translation: '(knowledge)',
    phonetic: '/noʊ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['I know where it is.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'See',
    translation: '(vision)',
    phonetic: '/siː/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['I can see the mountain from here.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Come',
    translation: '(approach)',
    phonetic: '/kʌm/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Come here, please.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Eat',
    translation: '(consume food)',
    phonetic: '/iːt/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['I eat breakfast at seven.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Drink',
    translation: '(consume liquid)',
    phonetic: '/drɪŋk/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['I drink water every day.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Speak',
    translation: '(verbal communication)',
    phonetic: '/spiːk/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['I speak a little English.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Understand',
    translation: '(comprehend)',
    phonetic: '/ˌʌndərˈstænd/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['I understand the question.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Work',
    translation: '(employment/effort)',
    phonetic: '/wɜːrk/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['I work in an office.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Live',
    translation: '(reside)',
    phonetic: '/lɪv/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['I live in this city.'],
    milestoneTags: ['onboarding'],
  },

  // ── Polite Phrases (8) ─────────────────────────────────────────
  {
    word: 'Excuse me',
    translation: '(polite interruption)',
    phonetic: '/ɪkˈskjuːz miː/',
    category: 'polite',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Excuse me, where is the exit?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Sorry',
    translation: '(apology)',
    phonetic: '/ˈsɒri/',
    category: 'polite',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Sorry, I did not hear you.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: "You're welcome",
    translation: '(response to thanks)',
    phonetic: '/jʊr ˈwɛlkəm/',
    category: 'polite',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["You're welcome, it was no trouble."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Could you repeat that?',
    translation: '(request repetition)',
    phonetic: '/kʊd juː rɪˈpiːt ðæt/',
    category: 'polite',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Could you repeat that more slowly?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'I would like',
    translation: '(polite request)',
    phonetic: '/aɪ wʊd laɪk/',
    category: 'polite',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['I would like a table for two.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'May I',
    translation: '(polite permission)',
    phonetic: '/meɪ aɪ/',
    category: 'polite',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['May I sit here?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'No problem',
    translation: '(casual acceptance)',
    phonetic: '/noʊ ˈprɒbləm/',
    category: 'polite',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['No problem, take your time.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Of course',
    translation: '(willing agreement)',
    phonetic: '/əv kɔːrs/',
    category: 'polite',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Of course, I can help you.'],
    milestoneTags: ['onboarding'],
  },

  // ── Emergency / Survival (7) ───────────────────────────────────
  {
    word: 'Help',
    translation: '(request assistance)',
    phonetic: '/hɛlp/',
    category: 'emergency',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['I need help!'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Hospital',
    translation: '(medical facility)',
    phonetic: '/ˈhɒspɪtl/',
    category: 'emergency',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Where is the nearest hospital?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Police',
    translation: '(law enforcement)',
    phonetic: '/pəˈliːs/',
    category: 'emergency',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Call the police, please.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Bathroom',
    translation: '(restroom)',
    phonetic: '/ˈbæθruːm/',
    category: 'emergency',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Where is the bathroom?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'I am lost',
    translation: '(disorientation)',
    phonetic: '/aɪ æm lɒst/',
    category: 'emergency',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['I am lost. Can you show me on the map?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'I do not feel well',
    translation: '(illness)',
    phonetic: '/aɪ duː nɒt fiːl wɛl/',
    category: 'emergency',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['I do not feel well, I need to sit down.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Emergency',
    translation: '(urgent situation)',
    phonetic: '/ɪˈmɜːrdʒənsi/',
    category: 'emergency',
    cefrLevel: 'A2',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['This is an emergency, please hurry.'],
    milestoneTags: ['onboarding'],
  },

  // ── Time & Numbers (10) ────────────────────────────────────────
  {
    word: 'Today',
    translation: '(current day)',
    phonetic: '/təˈdeɪ/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['I have a meeting today.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Tomorrow',
    translation: '(next day)',
    phonetic: '/təˈmɒroʊ/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['I will call you tomorrow.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Yesterday',
    translation: '(previous day)',
    phonetic: '/ˈjɛstərdeɪ/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['I arrived yesterday.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Now',
    translation: '(current moment)',
    phonetic: '/naʊ/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['I am ready now.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Later',
    translation: '(future moment)',
    phonetic: '/ˈleɪtər/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['I will do it later.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Morning',
    translation: '(early part of day)',
    phonetic: '/ˈmɔːrnɪŋ/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['I exercise every morning.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Night',
    translation: '(dark hours)',
    phonetic: '/naɪt/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['The restaurant is open at night.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Week',
    translation: '(seven days)',
    phonetic: '/wiːk/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['I will be there next week.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Hour',
    translation: '(sixty minutes)',
    phonetic: '/aʊər/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['The flight is one hour long.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'What time is it?',
    translation: '(asking the time)',
    phonetic: '/wɒt taɪm ɪz ɪt/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['What time is it? I have a meeting soon.'],
    milestoneTags: ['onboarding'],
  },

  // ── Connectors (7) ─────────────────────────────────────────────
  {
    word: 'And',
    translation: '(addition)',
    phonetic: '/ænd/',
    category: 'connector',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['I have a pen and a notebook.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'But',
    translation: '(contrast)',
    phonetic: '/bʌt/',
    category: 'connector',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['I am tired, but I will finish.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Because',
    translation: '(reason)',
    phonetic: '/bɪˈkɒz/',
    category: 'connector',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['I stayed home because it was raining.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Or',
    translation: '(alternative)',
    phonetic: '/ɔːr/',
    category: 'connector',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['Do you want tea or coffee?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'So',
    translation: '(consequence)',
    phonetic: '/soʊ/',
    category: 'connector',
    cefrLevel: 'A2',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['It was late, so I took a taxi.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Also',
    translation: '(in addition)',
    phonetic: '/ˈɔːlsoʊ/',
    category: 'connector',
    cefrLevel: 'A2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['I also speak French.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Then',
    translation: '(sequence)',
    phonetic: '/ðɛn/',
    category: 'connector',
    cefrLevel: 'A2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['First I eat, then I go to work.'],
    milestoneTags: ['onboarding'],
  },

  // ── Daily Essentials (12) ──────────────────────────────────────
  {
    word: 'Water',
    translation: '(H2O)',
    phonetic: '/ˈwɔːtər/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Can I have some water, please?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Food',
    translation: '(nourishment)',
    phonetic: '/fuːd/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['The food here is very good.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Money',
    translation: '(currency)',
    phonetic: '/ˈmʌni/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['I need to find an ATM for money.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'House',
    translation: '(dwelling)',
    phonetic: '/haʊs/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['My house is near the park.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Street',
    translation: '(road)',
    phonetic: '/striːt/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['The shop is on the next street.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Car',
    translation: '(automobile)',
    phonetic: '/kɑːr/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['I go to work by car.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Phone',
    translation: '(telephone)',
    phonetic: '/foʊn/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['My phone is not working.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Big',
    translation: '(large size)',
    phonetic: '/bɪɡ/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['This room is very big.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Small',
    translation: '(little size)',
    phonetic: '/smɔːl/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['I need a small bag.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Good',
    translation: '(positive quality)',
    phonetic: '/ɡʊd/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['This is a good restaurant.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Bad',
    translation: '(negative quality)',
    phonetic: '/bæd/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['The weather is bad today.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'New',
    translation: '(recently made)',
    phonetic: '/njuː/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['I have a new job.'],
    milestoneTags: ['onboarding'],
  },

  // ── Common Expressions (6) ─────────────────────────────────────
  {
    word: 'I do not understand',
    translation: '(lack of comprehension)',
    phonetic: '/aɪ duː nɒt ˌʌndərˈstænd/',
    category: 'expression',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['I do not understand, can you say it again?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'I think',
    translation: '(opinion marker)',
    phonetic: '/aɪ θɪŋk/',
    category: 'expression',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['I think the museum is closed today.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'I agree',
    translation: '(expressing agreement)',
    phonetic: '/aɪ əˈɡriː/',
    category: 'expression',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['I agree, that is a good idea.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Maybe',
    translation: '(possibility)',
    phonetic: '/ˈmeɪbi/',
    category: 'expression',
    cefrLevel: 'A2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Maybe we can go tomorrow.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'A lot',
    translation: '(large quantity)',
    phonetic: '/ə lɒt/',
    category: 'expression',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['I have a lot of work today.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Very',
    translation: '(intensifier)',
    phonetic: '/ˈvɛri/',
    category: 'expression',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['This coffee is very hot.'],
    milestoneTags: ['onboarding'],
  },
];
