import type { AddWordInput } from '@/lib/word-bank/types';

/**
 * 85 English words for B1-B2 learners.
 * Covers professional communication, nuanced verbs, opinions, business, and advanced daily vocabulary.
 */
export const ENGLISH_INTERMEDIATE: AddWordInput[] = [
  // ── Professional Greetings & Introductions (8) ─────────────────
  {
    word: 'I appreciate it',
    translation: '(formal gratitude)',
    phonetic: '/aɪ əˈpriːʃieɪt ɪt/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Thank you for the update, I appreciate it.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Looking forward to',
    translation: '(anticipation)',
    phonetic: '/ˈlʊkɪŋ ˈfɔːrwərd tuː/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['I am looking forward to our meeting.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'It was a pleasure',
    translation: '(formal farewell)',
    phonetic: '/ɪt wɒz ə ˈplɛʒər/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['It was a pleasure meeting you.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'How have you been?',
    translation: '(checking in)',
    phonetic: '/haʊ hæv juː biːn/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Long time no see — how have you been?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Let me introduce myself',
    translation: '(formal self-introduction)',
    phonetic: '/lɛt miː ˌɪntrəˈdjuːs maɪˈsɛlf/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Let me introduce myself, I am the project lead.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'On behalf of',
    translation: '(representing)',
    phonetic: '/ɒn bɪˈhɑːf əv/',
    category: 'greeting',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['On behalf of the team, welcome aboard.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Pleased to meet you',
    translation: '(formal introduction)',
    phonetic: '/pliːzd tə miːt juː/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Pleased to meet you, I have heard great things.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Take care',
    translation: '(warm farewell)',
    phonetic: '/teɪk kɛr/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Take care, and let me know if you need anything.'],
    milestoneTags: ['onboarding'],
  },

  // ── Business & Professional Questions (10) ─────────────────────
  {
    word: 'What do you think about',
    translation: '(requesting opinion)',
    phonetic: '/wɒt duː juː θɪŋk əˈbaʊt/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['What do you think about the new proposal?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Could you clarify',
    translation: '(requesting explanation)',
    phonetic: '/kʊd juː ˈklærɪfaɪ/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Could you clarify the deadline for this task?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Would it be possible',
    translation: '(polite possibility)',
    phonetic: '/wʊd ɪt biː ˈpɒsɪbl/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Would it be possible to reschedule?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'What are the next steps?',
    translation: '(planning)',
    phonetic: '/wɒt ɑːr ðə nɛkst stɛps/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Great discussion — what are the next steps?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'How would you approach',
    translation: '(soliciting strategy)',
    phonetic: '/haʊ wʊd juː əˈproʊtʃ/',
    category: 'question',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['How would you approach this problem?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Do you have any concerns?',
    translation: '(checking objections)',
    phonetic: '/duː juː hæv ˈɛni kənˈsɜːrnz/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Before we proceed, do you have any concerns?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Is there anything else?',
    translation: '(completeness check)',
    phonetic: '/ɪz ðɛr ˈɛniθɪŋ ɛls/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Is there anything else you need from me?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'What is your availability?',
    translation: '(scheduling)',
    phonetic: '/wɒt ɪz jʊr əˌveɪləˈbɪlɪti/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['What is your availability next week?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Could you elaborate on',
    translation: '(requesting detail)',
    phonetic: '/kʊd juː ɪˈlæbəreɪt ɒn/',
    category: 'question',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Could you elaborate on the budget figures?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'What is the status of',
    translation: '(progress inquiry)',
    phonetic: '/wɒt ɪz ðə ˈsteɪtəs əv/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['What is the status of the contract?'],
    milestoneTags: ['onboarding'],
  },

  // ── Advanced Verbs (14) ────────────────────────────────────────
  {
    word: 'Achieve',
    translation: '(accomplish a goal)',
    phonetic: '/əˈtʃiːv/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['We need to achieve our targets this quarter.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Improve',
    translation: '(make better)',
    phonetic: '/ɪmˈpruːv/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['How can we improve the process?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Consider',
    translation: '(think carefully)',
    phonetic: '/kənˈsɪdər/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['We should consider all the options.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Suggest',
    translation: '(propose an idea)',
    phonetic: '/səˈdʒɛst/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['I suggest we start with the data analysis.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Manage',
    translation: '(handle/oversee)',
    phonetic: '/ˈmænɪdʒ/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['She manages a team of twelve people.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Require',
    translation: '(need formally)',
    phonetic: '/rɪˈkwaɪər/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['This position requires three years of experience.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Provide',
    translation: '(supply/give)',
    phonetic: '/prəˈvaɪd/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['I can provide the documents by Friday.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Develop',
    translation: '(build/grow)',
    phonetic: '/dɪˈvɛləp/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['We are developing a new product line.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Negotiate',
    translation: '(discuss terms)',
    phonetic: '/nɪˈɡoʊʃieɪt/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['We need to negotiate the contract terms.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Implement',
    translation: '(put into action)',
    phonetic: '/ˈɪmplɪmɛnt/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['We will implement the changes next month.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Analyze',
    translation: '(examine in detail)',
    phonetic: '/ˈænəlaɪz/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Let me analyze the data before the meeting.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Resolve',
    translation: '(find a solution)',
    phonetic: '/rɪˈzɒlv/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['We need to resolve this issue quickly.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Collaborate',
    translation: '(work together)',
    phonetic: '/kəˈlæbəreɪt/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Our teams collaborate on cross-functional projects.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Prioritize',
    translation: '(rank by importance)',
    phonetic: '/praɪˈɒrɪtaɪz/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['We need to prioritize the most urgent tasks.'],
    milestoneTags: ['onboarding'],
  },

  // ── Polite / Diplomatic Phrases (7) ────────────────────────────
  {
    word: 'I see your point',
    translation: '(acknowledging perspective)',
    phonetic: '/aɪ siː jʊr pɔɪnt/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['I see your point, but have you considered the cost?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'With all due respect',
    translation: '(polite disagreement)',
    phonetic: '/wɪð ɔːl djuː rɪˈspɛkt/',
    category: 'polite',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['With all due respect, I disagree with that approach.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'I was wondering if',
    translation: '(soft request)',
    phonetic: '/aɪ wɒz ˈwʌndərɪŋ ɪf/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['I was wondering if you could send me the report.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'I am afraid that',
    translation: '(delivering bad news)',
    phonetic: '/aɪ æm əˈfreɪd ðæt/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['I am afraid that we cannot meet that deadline.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'As far as I know',
    translation: '(qualified certainty)',
    phonetic: '/æz fɑːr æz aɪ noʊ/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['As far as I know, the project is on track.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Would you mind',
    translation: '(polite request)',
    phonetic: '/wʊd juː maɪnd/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Would you mind closing the door?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'To be honest',
    translation: '(candid opinion)',
    phonetic: '/tə biː ˈɒnɪst/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['To be honest, I think we need more time.'],
    milestoneTags: ['onboarding'],
  },

  // ── Emergency / Travel (6) ─────────────────────────────────────
  {
    word: 'I need to cancel',
    translation: '(cancellation)',
    phonetic: '/aɪ niːd tə ˈkænsəl/',
    category: 'emergency',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['I need to cancel my reservation.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'I have a complaint',
    translation: '(expressing dissatisfaction)',
    phonetic: '/aɪ hæv ə kəmˈpleɪnt/',
    category: 'emergency',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['I have a complaint about the service.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Insurance',
    translation: '(risk coverage)',
    phonetic: '/ɪnˈʃʊrəns/',
    category: 'emergency',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Do you have travel insurance?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Appointment',
    translation: '(scheduled meeting)',
    phonetic: '/əˈpɔɪntmənt/',
    category: 'emergency',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['I have an appointment at three o\'clock.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Prescription',
    translation: '(medical order)',
    phonetic: '/prɪˈskrɪpʃən/',
    category: 'emergency',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['I need to fill this prescription at the pharmacy.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Embassy',
    translation: '(diplomatic office)',
    phonetic: '/ˈɛmbəsi/',
    category: 'emergency',
    cefrLevel: 'B2',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['I need to contact my embassy.'],
    milestoneTags: ['onboarding'],
  },

  // ── Time & Scheduling (8) ──────────────────────────────────────
  {
    word: 'Deadline',
    translation: '(time limit)',
    phonetic: '/ˈdɛdlaɪn/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['The deadline is next Friday.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Schedule',
    translation: '(timetable)',
    phonetic: '/ˈʃɛdjuːl/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Let me check my schedule.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'In advance',
    translation: '(beforehand)',
    phonetic: '/ɪn ədˈvɑːns/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Please let me know in advance.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'As soon as possible',
    translation: '(urgency marker)',
    phonetic: '/æz suːn æz ˈpɒsɪbl/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Please reply as soon as possible.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Meanwhile',
    translation: '(during that time)',
    phonetic: '/ˈmiːnwaɪl/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Meanwhile, I will prepare the presentation.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Eventually',
    translation: '(in the end)',
    phonetic: '/ɪˈvɛntʃuəli/',
    category: 'time',
    cefrLevel: 'B2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['We will eventually find a solution.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Recently',
    translation: '(not long ago)',
    phonetic: '/ˈriːsəntli/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['I recently moved to a new apartment.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'From now on',
    translation: '(starting now)',
    phonetic: '/frɒm naʊ ɒn/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['From now on, meetings start at nine.'],
    milestoneTags: ['onboarding'],
  },

  // ── Connectors & Discourse (8) ─────────────────────────────────
  {
    word: 'However',
    translation: '(contrast)',
    phonetic: '/haʊˈɛvər/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['The plan is good; however, the budget is tight.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Therefore',
    translation: '(conclusion)',
    phonetic: '/ˈðɛrfɔːr/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['The data is clear; therefore, we should proceed.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Although',
    translation: '(concession)',
    phonetic: '/ɔːlˈðoʊ/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['Although it was difficult, we completed the project.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Furthermore',
    translation: '(adding information)',
    phonetic: '/ˈfɜːrðərmɔːr/',
    category: 'connector',
    cefrLevel: 'B2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Furthermore, we need to consider the timeline.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'In addition',
    translation: '(supplementary)',
    phonetic: '/ɪn əˈdɪʃən/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['In addition, we have secured new funding.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'On the other hand',
    translation: '(alternative view)',
    phonetic: '/ɒn ðə ˈʌðər hænd/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['On the other hand, this approach saves time.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'As a result',
    translation: '(consequence)',
    phonetic: '/æz ə rɪˈzʌlt/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Sales dropped; as a result, we adjusted our strategy.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Nevertheless',
    translation: '(despite that)',
    phonetic: '/ˌnɛvərðəˈlɛs/',
    category: 'connector',
    cefrLevel: 'B2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['It was risky; nevertheless, we decided to invest.'],
    milestoneTags: ['onboarding'],
  },

  // ── Daily / Professional Essentials (12) ───────────────────────
  {
    word: 'Budget',
    translation: '(financial plan)',
    phonetic: '/ˈbʌdʒɪt/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['We need to stay within the budget.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Feedback',
    translation: '(response/evaluation)',
    phonetic: '/ˈfiːdbæk/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['I would appreciate your feedback on this draft.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Opportunity',
    translation: '(favorable chance)',
    phonetic: '/ˌɒpərˈtjuːnɪti/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['This is a great opportunity for growth.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Challenge',
    translation: '(difficult task)',
    phonetic: '/ˈtʃælɪndʒ/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['The biggest challenge is the tight timeline.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Experience',
    translation: '(knowledge from practice)',
    phonetic: '/ɪkˈspɪriəns/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['I have five years of experience in marketing.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Efficient',
    translation: '(productive with minimal waste)',
    phonetic: '/ɪˈfɪʃənt/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['We need a more efficient workflow.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Available',
    translation: '(accessible/free)',
    phonetic: '/əˈveɪləbl/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['I am available on Tuesday afternoon.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Responsible',
    translation: '(accountable)',
    phonetic: '/rɪˈspɒnsɪbl/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['She is responsible for the marketing team.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Significant',
    translation: '(important/notable)',
    phonetic: '/sɪɡˈnɪfɪkənt/',
    category: 'daily',
    cefrLevel: 'B2',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['There has been a significant improvement.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Appropriate',
    translation: '(suitable)',
    phonetic: '/əˈproʊpriɪt/',
    category: 'daily',
    cefrLevel: 'B2',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Is this the appropriate time to discuss it?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Comprehensive',
    translation: '(thorough/complete)',
    phonetic: '/ˌkɒmprɪˈhɛnsɪv/',
    category: 'daily',
    cefrLevel: 'B2',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['We need a comprehensive review of the plan.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Reliable',
    translation: '(dependable)',
    phonetic: '/rɪˈlaɪəbl/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['He is the most reliable person on the team.'],
    milestoneTags: ['onboarding'],
  },

  // ── Expressions & Opinions (12) ────────────────────────────────
  {
    word: 'In my opinion',
    translation: '(personal view)',
    phonetic: '/ɪn maɪ əˈpɪnjən/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['In my opinion, we should wait.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'It depends on',
    translation: '(conditional)',
    phonetic: '/ɪt dɪˈpɛndz ɒn/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['It depends on the client\'s decision.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'That makes sense',
    translation: '(understanding)',
    phonetic: '/ðæt meɪks sɛns/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['That makes sense, let us move forward.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'I am not sure',
    translation: '(uncertainty)',
    phonetic: '/aɪ æm nɒt ʃʊr/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['I am not sure about the exact date.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'It turned out that',
    translation: '(unexpected result)',
    phonetic: '/ɪt tɜːrnd aʊt ðæt/',
    category: 'expression',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['It turned out that the report was incorrect.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'As a matter of fact',
    translation: '(actually/in truth)',
    phonetic: '/æz ə ˈmætər əv fækt/',
    category: 'expression',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['As a matter of fact, I have already started.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'For instance',
    translation: '(example)',
    phonetic: '/fɔːr ˈɪnstəns/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['For instance, we could reduce costs by outsourcing.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Basically',
    translation: '(in essence)',
    phonetic: '/ˈbeɪsɪkli/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Basically, we need to start over.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Obviously',
    translation: '(clearly)',
    phonetic: '/ˈɒbviəsli/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Obviously, the first step is to gather data.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Apparently',
    translation: '(it seems)',
    phonetic: '/əˈpærəntli/',
    category: 'expression',
    cefrLevel: 'B2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Apparently, the meeting has been moved to Thursday.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'At least',
    translation: '(minimum)',
    phonetic: '/æt liːst/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['It will take at least two weeks.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'More or less',
    translation: '(approximately)',
    phonetic: '/mɔːr ɔːr lɛs/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['The project is more or less on schedule.'],
    milestoneTags: ['onboarding'],
  },
];
