import type { AddWordInput } from '@/lib/word-bank/types';

/**
 * 85 French words for B1-B2 learners.
 * Covers professional communication, nuanced verbs, opinions, business, and advanced daily vocabulary.
 */
export const FRENCH_INTERMEDIATE: AddWordInput[] = [
  // ── Professional Greetings & Introductions (8) ─────────────────
  {
    word: "Je vous en prie",
    translation: '(formal you are welcome)',
    phonetic: '/ʒə vu zɑ̃ pʁi/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Merci beaucoup. — Je vous en prie.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: "J'ai hâte de",
    translation: '(I look forward to)',
    phonetic: '/ʒe ɑt də/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["J'ai hâte de vous revoir."],
    milestoneTags: ['onboarding'],
  },
  {
    word: "C'était un plaisir",
    translation: '(it was a pleasure)',
    phonetic: '/setɛ œ̃ plɛziʁ/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["C'était un plaisir de travailler avec vous."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Comment allez-vous ?',
    translation: '(how are you — formal)',
    phonetic: '/kɔmɑ̃ tale vu/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Comment allez-vous depuis la dernière fois ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Permettez-moi de me présenter',
    translation: '(allow me to introduce myself)',
    phonetic: '/pɛʁmɛte mwa də mə pʁezɑ̃te/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Permettez-moi de me présenter, je suis le directeur.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: "Au nom de l'équipe",
    translation: '(on behalf of the team)',
    phonetic: '/o nɔ̃ də lekip/',
    category: 'greeting',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["Au nom de l'équipe, bienvenue parmi nous."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Ravi de vous rencontrer',
    translation: '(delighted to meet you)',
    phonetic: '/ʁavi də vu ʁɑ̃kɔ̃tʁe/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Ravi de vous rencontrer, on m\'a beaucoup parlé de vous.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Prenez soin de vous',
    translation: '(take care)',
    phonetic: '/pʁəne swɛ̃ də vu/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["Prenez soin de vous, et n'hésitez pas à me contacter."],
    milestoneTags: ['onboarding'],
  },

  // ── Business & Professional Questions (10) ─────────────────────
  {
    word: "Qu'en pensez-vous ?",
    translation: '(what do you think about it?)',
    phonetic: '/kɑ̃ pɑ̃se vu/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["Voici la proposition, qu'en pensez-vous ?"],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Pourriez-vous préciser',
    translation: '(could you clarify)',
    phonetic: '/puʁje vu pʁesise/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Pourriez-vous préciser la date limite ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Serait-il possible de',
    translation: '(would it be possible to)',
    phonetic: '/səʁɛ til pɔsibl də/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Serait-il possible de reporter la réunion ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Quelles sont les prochaines étapes ?',
    translation: '(what are the next steps?)',
    phonetic: '/kɛl sɔ̃ le pʁɔʃɛn etap/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Bonne discussion — quelles sont les prochaines étapes ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Comment aborderiez-vous',
    translation: '(how would you approach)',
    phonetic: '/kɔmɑ̃ abɔʁdəʁje vu/',
    category: 'question',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Comment aborderiez-vous ce problème ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Avez-vous des inquiétudes ?',
    translation: '(do you have any concerns?)',
    phonetic: '/ave vu de zɛ̃kjetyd/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Avant de continuer, avez-vous des inquiétudes ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: "Y a-t-il autre chose ?",
    translation: '(is there anything else?)',
    phonetic: '/i a til otʁ ʃoz/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Y a-t-il autre chose dont vous avez besoin ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Quelles sont vos disponibilités ?',
    translation: '(what is your availability?)',
    phonetic: '/kɛl sɔ̃ vo dispɔnibilite/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Quelles sont vos disponibilités la semaine prochaine ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Pourriez-vous développer',
    translation: '(could you elaborate)',
    phonetic: '/puʁje vu devlɔpe/',
    category: 'question',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Pourriez-vous développer ce point ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: "Où en est le dossier ?",
    translation: '(what is the status?)',
    phonetic: '/u ɑ̃ ɛ lə dosje/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Où en est le dossier du contrat ?'],
    milestoneTags: ['onboarding'],
  },

  // ── Advanced Verbs (14) ────────────────────────────────────────
  {
    word: 'Atteindre',
    translation: '(to achieve/reach)',
    phonetic: '/atɛ̃dʁ/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Nous devons atteindre nos objectifs ce trimestre.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Améliorer',
    translation: '(to improve)',
    phonetic: '/ameljɔʁe/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Comment pouvons-nous améliorer le processus ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Envisager',
    translation: '(to consider)',
    phonetic: '/ɑ̃vizaʒe/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Nous devrions envisager toutes les options.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Proposer',
    translation: '(to suggest/propose)',
    phonetic: '/pʁɔpoze/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ["Je propose que nous commencions par l'analyse."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Gérer',
    translation: '(to manage)',
    phonetic: '/ʒeʁe/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Elle gère une équipe de douze personnes.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Exiger',
    translation: '(to require/demand)',
    phonetic: '/ɛɡziʒe/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ["Ce poste exige trois ans d'expérience."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Fournir',
    translation: '(to provide/supply)',
    phonetic: '/fuʁniʁ/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Je peux fournir les documents vendredi.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Développer',
    translation: '(to develop)',
    phonetic: '/devlɔpe/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Nous développons une nouvelle gamme de produits.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Négocier',
    translation: '(to negotiate)',
    phonetic: '/neɡɔsje/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Nous devons négocier les termes du contrat.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Mettre en œuvre',
    translation: '(to implement)',
    phonetic: '/mɛtʁ ɑ̃ nœvʁ/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Nous allons mettre en œuvre les changements le mois prochain.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Analyser',
    translation: '(to analyze)',
    phonetic: '/analize/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Laissez-moi analyser les données avant la réunion.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Résoudre',
    translation: '(to resolve/solve)',
    phonetic: '/ʁezudʁ/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Nous devons résoudre ce problème rapidement.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Collaborer',
    translation: '(to collaborate)',
    phonetic: '/kɔlabɔʁe/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Nos équipes collaborent sur des projets transversaux.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Prioriser',
    translation: '(to prioritize)',
    phonetic: '/pʁijɔʁize/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Nous devons prioriser les tâches les plus urgentes.'],
    milestoneTags: ['onboarding'],
  },

  // ── Polite / Diplomatic Phrases (7) ────────────────────────────
  {
    word: 'Je comprends votre point de vue',
    translation: '(I see your point)',
    phonetic: '/ʒə kɔ̃pʁɑ̃ vɔtʁ pwɛ̃ də vy/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Je comprends votre point de vue, mais avez-vous pensé au coût ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Avec tout le respect que je vous dois',
    translation: '(with all due respect)',
    phonetic: '/avɛk tu lə ʁɛspɛ kə ʒə vu dwa/',
    category: 'polite',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["Avec tout le respect que je vous dois, je ne suis pas d'accord."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Je me demandais si',
    translation: '(I was wondering if)',
    phonetic: '/ʒə mə dəmɑ̃dɛ si/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["Je me demandais si vous pouviez m'envoyer le rapport."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Je crains que',
    translation: '(I am afraid that)',
    phonetic: '/ʒə kʁɛ̃ kə/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Je crains que nous ne puissions pas respecter ce délai.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'À ma connaissance',
    translation: '(as far as I know)',
    phonetic: '/a ma kɔnɛsɑ̃s/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['À ma connaissance, le projet avance bien.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Cela vous dérangerait-il de',
    translation: '(would you mind)',
    phonetic: '/sla vu deʁɑ̃ʒʁɛ til də/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Cela vous dérangerait-il de fermer la porte ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Pour être honnête',
    translation: '(to be honest)',
    phonetic: '/puʁ ɛtʁ ɔnɛt/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Pour être honnête, je pense que nous avons besoin de plus de temps.'],
    milestoneTags: ['onboarding'],
  },

  // ── Emergency / Travel (6) ─────────────────────────────────────
  {
    word: 'Je dois annuler',
    translation: '(I need to cancel)',
    phonetic: '/ʒə dwa anyle/',
    category: 'emergency',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Je dois annuler ma réservation.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Je souhaite faire une réclamation',
    translation: '(I wish to make a complaint)',
    phonetic: '/ʒə swɛt fɛʁ yn ʁeklamasjɔ̃/',
    category: 'emergency',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Je souhaite faire une réclamation concernant le service.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Assurance',
    translation: '(insurance)',
    phonetic: '/asyʁɑ̃s/',
    category: 'emergency',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Avez-vous une assurance voyage ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Rendez-vous',
    translation: '(appointment)',
    phonetic: '/ʁɑ̃de vu/',
    category: 'emergency',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ["J'ai un rendez-vous à quinze heures."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Ordonnance',
    translation: '(prescription)',
    phonetic: '/ɔʁdɔnɑ̃s/',
    category: 'emergency',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Je dois faire préparer cette ordonnance à la pharmacie.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Ambassade',
    translation: '(embassy)',
    phonetic: '/ɑ̃basad/',
    category: 'emergency',
    cefrLevel: 'B2',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Je dois contacter mon ambassade.'],
    milestoneTags: ['onboarding'],
  },

  // ── Time & Scheduling (8) ─────────────────────────────────────
  {
    word: 'Date limite',
    translation: '(deadline)',
    phonetic: '/dat limit/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['La date limite est vendredi prochain.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Emploi du temps',
    translation: '(schedule)',
    phonetic: '/ɑ̃plwa dy tɑ̃/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Laissez-moi vérifier mon emploi du temps.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: "À l'avance",
    translation: '(in advance)',
    phonetic: '/a lavɑ̃s/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["Prévenez-moi à l'avance, s'il vous plaît."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Dès que possible',
    translation: '(as soon as possible)',
    phonetic: '/dɛ kə pɔsibl/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Veuillez répondre dès que possible.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'En attendant',
    translation: '(meanwhile)',
    phonetic: '/ɑ̃ natɑ̃dɑ̃/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['En attendant, je vais préparer la présentation.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Finalement',
    translation: '(eventually/finally)',
    phonetic: '/finalmɑ̃/',
    category: 'time',
    cefrLevel: 'B2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Finalement, nous trouverons une solution.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Récemment',
    translation: '(recently)',
    phonetic: '/ʁesamɑ̃/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['J\'ai récemment déménagé.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Dorénavant',
    translation: '(from now on)',
    phonetic: '/dɔʁenavɑ̃/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Dorénavant, les réunions commencent à neuf heures.'],
    milestoneTags: ['onboarding'],
  },

  // ── Connectors & Discourse (8) ─────────────────────────────────
  {
    word: 'Cependant',
    translation: '(however)',
    phonetic: '/səpɑ̃dɑ̃/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Le plan est bon ; cependant, le budget est serré.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Par conséquent',
    translation: '(therefore)',
    phonetic: '/paʁ kɔ̃sekɑ̃/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Les données sont claires ; par conséquent, nous devrions avancer.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Bien que',
    translation: '(although)',
    phonetic: '/bjɛ̃ kə/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['Bien que ce fût difficile, nous avons terminé le projet.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'De plus',
    translation: '(furthermore)',
    phonetic: '/də plys/',
    category: 'connector',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['De plus, nous devons considérer le calendrier.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'En outre',
    translation: '(in addition)',
    phonetic: '/ɑ̃ nutʁ/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['En outre, nous avons obtenu de nouveaux financements.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: "D'un autre côté",
    translation: '(on the other hand)',
    phonetic: '/dœ̃ notʁ kote/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["D'un autre côté, cette approche fait gagner du temps."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'En conséquence',
    translation: '(as a result)',
    phonetic: '/ɑ̃ kɔ̃sekɑ̃s/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Les ventes ont baissé ; en conséquence, nous avons ajusté la stratégie.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Néanmoins',
    translation: '(nevertheless)',
    phonetic: '/neɑ̃mwɛ̃/',
    category: 'connector',
    cefrLevel: 'B2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ["C'était risqué ; néanmoins, nous avons décidé d'investir."],
    milestoneTags: ['onboarding'],
  },

  // ── Daily / Professional Essentials (12) ───────────────────────
  {
    word: 'Budget',
    translation: '(budget)',
    phonetic: '/bydʒɛ/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Nous devons rester dans le budget.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Retour',
    translation: '(feedback)',
    phonetic: '/ʁətuʁ/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ["J'apprécierais votre retour sur ce document."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Opportunité',
    translation: '(opportunity)',
    phonetic: '/ɔpɔʁtynite/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ["C'est une excellente opportunité de croissance."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Défi',
    translation: '(challenge)',
    phonetic: '/defi/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Le plus grand défi est le calendrier serré.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Expérience',
    translation: '(experience)',
    phonetic: '/ɛkspeʁjɑ̃s/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ["J'ai cinq ans d'expérience en marketing."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Efficace',
    translation: '(efficient)',
    phonetic: '/efikas/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Nous avons besoin d\'un processus plus efficace.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Disponible',
    translation: '(available)',
    phonetic: '/dispɔnibl/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Je suis disponible mardi après-midi.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Responsable',
    translation: '(responsible)',
    phonetic: '/ʁɛspɔ̃sabl/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Elle est responsable de l\'équipe marketing.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Important',
    translation: '(significant/important)',
    phonetic: '/ɛ̃pɔʁtɑ̃/',
    category: 'daily',
    cefrLevel: 'B2',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Il y a eu une amélioration importante.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Approprié',
    translation: '(appropriate)',
    phonetic: '/apʁɔpʁije/',
    category: 'daily',
    cefrLevel: 'B2',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ["Est-ce le moment approprié pour en discuter ?"],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Complet',
    translation: '(comprehensive/complete)',
    phonetic: '/kɔ̃plɛ/',
    category: 'daily',
    cefrLevel: 'B2',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Nous avons besoin d\'un examen complet du plan.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Fiable',
    translation: '(reliable)',
    phonetic: '/fjabl/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ["C'est la personne la plus fiable de l'équipe."],
    milestoneTags: ['onboarding'],
  },

  // ── Expressions & Opinions (12) ────────────────────────────────
  {
    word: 'À mon avis',
    translation: '(in my opinion)',
    phonetic: '/a mɔ̃ navi/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['À mon avis, nous devrions attendre.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Ça dépend de',
    translation: '(it depends on)',
    phonetic: '/sa depɑ̃ də/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Ça dépend de la décision du client.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: "C'est logique",
    translation: '(that makes sense)',
    phonetic: '/sɛ lɔʒik/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["C'est logique, avançons."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Je ne suis pas sûr',
    translation: '(I am not sure)',
    phonetic: '/ʒə nə sɥi pɑ syʁ/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Je ne suis pas sûr de la date exacte.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Il s\'est avéré que',
    translation: '(it turned out that)',
    phonetic: '/il sɛ taveʁe kə/',
    category: 'expression',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Il s\'est avéré que le rapport était incorrect.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'En fait',
    translation: '(as a matter of fact)',
    phonetic: '/ɑ̃ fɛ/',
    category: 'expression',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['En fait, j\'ai déjà commencé.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Par exemple',
    translation: '(for instance)',
    phonetic: '/paʁ ɛɡzɑ̃pl/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Par exemple, nous pourrions réduire les coûts.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'En gros',
    translation: '(basically)',
    phonetic: '/ɑ̃ ɡʁo/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['En gros, nous devons tout recommencer.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Évidemment',
    translation: '(obviously)',
    phonetic: '/evidamɑ̃/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Évidemment, la première étape est de collecter les données.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Apparemment',
    translation: '(apparently)',
    phonetic: '/apaʁamɑ̃/',
    category: 'expression',
    cefrLevel: 'B2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Apparemment, la réunion a été déplacée à jeudi.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Au moins',
    translation: '(at least)',
    phonetic: '/o mwɛ̃/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Cela prendra au moins deux semaines.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Plus ou moins',
    translation: '(more or less)',
    phonetic: '/plys u mwɛ̃/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Le projet est plus ou moins dans les temps.'],
    milestoneTags: ['onboarding'],
  },
];
