import type { AddWordInput } from '@/lib/word-bank/types';

/**
 * 85 core French words for A1-A2 learners.
 * Covers greetings, essential verbs, daily life, time, polite phrases, and survival vocabulary.
 */
export const FRENCH_BEGINNER: AddWordInput[] = [
  // ── Greetings & Introductions (10) ─────────────────────────────
  {
    word: 'Bonjour',
    translation: '(greeting)',
    phonetic: '/bɔ̃ʒuʁ/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Bonjour, comment allez-vous ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Au revoir',
    translation: '(farewell)',
    phonetic: '/o ʁəvwaʁ/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Au revoir, à bientôt !'],
    milestoneTags: ['onboarding'],
  },
  {
    word: "S'il vous plaît",
    translation: '(please — formal)',
    phonetic: '/sil vu plɛ/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["Un café, s'il vous plaît."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Merci',
    translation: '(thank you)',
    phonetic: '/mɛʁsi/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Merci beaucoup pour votre aide.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Oui',
    translation: '(yes)',
    phonetic: '/wi/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Oui, je comprends.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Non',
    translation: '(no)',
    phonetic: '/nɔ̃/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Non, merci.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Bonsoir',
    translation: '(good evening)',
    phonetic: '/bɔ̃swaʁ/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Bonsoir, bienvenue au restaurant.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Bonne nuit',
    translation: '(good night)',
    phonetic: '/bɔn nɥi/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Bonne nuit, dormez bien.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: "Je m'appelle",
    translation: '(my name is)',
    phonetic: '/ʒə mapɛl/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["Je m'appelle Marie."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Enchanté',
    translation: '(nice to meet you)',
    phonetic: '/ɑ̃ʃɑ̃te/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Enchanté, je suis Pierre.'],
    milestoneTags: ['onboarding'],
  },

  // ── Common Questions (10) ──────────────────────────────────────
  {
    word: 'Quoi',
    translation: '(what)',
    phonetic: '/kwa/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ["C'est quoi, ça ?"],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Où',
    translation: '(where)',
    phonetic: '/u/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Où est la gare ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Quand',
    translation: '(when)',
    phonetic: '/kɑ̃/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Quand est-ce que le bus arrive ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Comment',
    translation: '(how)',
    phonetic: '/kɔmɑ̃/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Comment allez-vous ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Pourquoi',
    translation: '(why)',
    phonetic: '/puʁkwa/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Pourquoi le magasin est fermé ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Qui',
    translation: '(who)',
    phonetic: '/ki/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['Qui est votre professeur ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Combien',
    translation: '(how much/many)',
    phonetic: '/kɔ̃bjɛ̃/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Combien ça coûte ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Parlez-vous anglais ?',
    translation: '(do you speak English?)',
    phonetic: '/paʁle vu ɑ̃ɡlɛ/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Excusez-moi, parlez-vous anglais ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Pouvez-vous m\'aider ?',
    translation: '(can you help me?)',
    phonetic: '/puve vu mede/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["Pouvez-vous m'aider à trouver l'hôtel ?"],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Quel',
    translation: '(which)',
    phonetic: '/kɛl/',
    category: 'question',
    cefrLevel: 'A2',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['Quel est votre numéro de téléphone ?'],
    milestoneTags: ['onboarding'],
  },

  // ── Essential Verbs (15) ───────────────────────────────────────
  {
    word: 'Être',
    translation: '(to be)',
    phonetic: '/ɛtʁ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Je suis étudiant.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Avoir',
    translation: '(to have)',
    phonetic: '/avwaʁ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ["J'ai deux frères."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Aller',
    translation: '(to go)',
    phonetic: '/ale/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Je vais au travail chaque jour.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Vouloir',
    translation: '(to want)',
    phonetic: '/vulwaʁ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ["Je voudrais un verre d'eau."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Pouvoir',
    translation: '(to be able to)',
    phonetic: '/puvwaʁ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Je peux vous aider.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Faire',
    translation: '(to do/make)',
    phonetic: '/fɛʁ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Que faites-vous dans la vie ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Savoir',
    translation: '(to know — facts)',
    phonetic: '/savwaʁ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Je sais où il est.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Voir',
    translation: '(to see)',
    phonetic: '/vwaʁ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ["Je vois la montagne d'ici."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Venir',
    translation: '(to come)',
    phonetic: '/vəniʁ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ["Venez ici, s'il vous plaît."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Manger',
    translation: '(to eat)',
    phonetic: '/mɑ̃ʒe/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Je mange le petit déjeuner à sept heures.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Boire',
    translation: '(to drink)',
    phonetic: '/bwaʁ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ["Je bois de l'eau tous les jours."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Parler',
    translation: '(to speak)',
    phonetic: '/paʁle/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Je parle un peu français.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Comprendre',
    translation: '(to understand)',
    phonetic: '/kɔ̃pʁɑ̃dʁ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Je comprends la question.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Travailler',
    translation: '(to work)',
    phonetic: '/tʁavaje/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Je travaille dans un bureau.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Habiter',
    translation: '(to live/reside)',
    phonetic: '/abite/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ["J'habite dans cette ville."],
    milestoneTags: ['onboarding'],
  },

  // ── Polite Phrases (8) ─────────────────────────────────────────
  {
    word: 'Excusez-moi',
    translation: '(excuse me — formal)',
    phonetic: '/ɛkskyze mwa/',
    category: 'polite',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Excusez-moi, où est la sortie ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Pardon',
    translation: '(sorry/pardon)',
    phonetic: '/paʁdɔ̃/',
    category: 'polite',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["Pardon, je n'ai pas entendu."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'De rien',
    translation: '(you are welcome)',
    phonetic: '/də ʁjɛ̃/',
    category: 'polite',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['De rien, avec plaisir.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Pouvez-vous répéter ?',
    translation: '(can you repeat?)',
    phonetic: '/puve vu ʁepete/',
    category: 'polite',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Pouvez-vous répéter plus lentement ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Je voudrais',
    translation: '(I would like)',
    phonetic: '/ʒə vudʁɛ/',
    category: 'polite',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Je voudrais une table pour deux.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Est-ce que je peux',
    translation: '(may I)',
    phonetic: '/ɛs kə ʒə pø/',
    category: 'polite',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["Est-ce que je peux m'asseoir ici ?"],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Pas de problème',
    translation: '(no problem)',
    phonetic: '/pɑ də pʁɔblɛm/',
    category: 'polite',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Pas de problème, prenez votre temps.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Bien sûr',
    translation: '(of course)',
    phonetic: '/bjɛ̃ syʁ/',
    category: 'polite',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Bien sûr, je peux vous aider.'],
    milestoneTags: ['onboarding'],
  },

  // ── Emergency / Survival (7) ───────────────────────────────────
  {
    word: 'Au secours',
    translation: '(help!)',
    phonetic: '/o səkuʁ/',
    category: 'emergency',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["Au secours, j'ai besoin d'aide !"],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Hôpital',
    translation: '(hospital)',
    phonetic: '/opital/',
    category: 'emergency',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ["Où est l'hôpital le plus proche ?"],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Police',
    translation: '(police)',
    phonetic: '/pɔlis/',
    category: 'emergency',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ["Appelez la police, s'il vous plaît."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Toilettes',
    translation: '(bathroom/restroom)',
    phonetic: '/twalɛt/',
    category: 'emergency',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Où sont les toilettes ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Je suis perdu',
    translation: '(I am lost)',
    phonetic: '/ʒə sɥi pɛʁdy/',
    category: 'emergency',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Je suis perdu, pouvez-vous me montrer sur la carte ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Je ne me sens pas bien',
    translation: '(I do not feel well)',
    phonetic: '/ʒə nə mə sɑ̃ pɑ bjɛ̃/',
    category: 'emergency',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["Je ne me sens pas bien, j'ai besoin de m'asseoir."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Urgence',
    translation: '(emergency)',
    phonetic: '/yʁʒɑ̃s/',
    category: 'emergency',
    cefrLevel: 'A2',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ["C'est une urgence, dépêchez-vous."],
    milestoneTags: ['onboarding'],
  },

  // ── Time & Numbers (10) ────────────────────────────────────────
  {
    word: "Aujourd'hui",
    translation: '(today)',
    phonetic: '/oʒuʁdɥi/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ["J'ai une réunion aujourd'hui."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Demain',
    translation: '(tomorrow)',
    phonetic: '/dəmɛ̃/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Je vous appellerai demain.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Hier',
    translation: '(yesterday)',
    phonetic: '/jɛʁ/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Je suis arrivé hier.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Maintenant',
    translation: '(now)',
    phonetic: '/mɛ̃tnɑ̃/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Je suis prêt maintenant.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Plus tard',
    translation: '(later)',
    phonetic: '/ply taʁ/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Je le ferai plus tard.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Matin',
    translation: '(morning)',
    phonetic: '/matɛ̃/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Je fais du sport chaque matin.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Nuit',
    translation: '(night)',
    phonetic: '/nɥi/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Le restaurant est ouvert la nuit.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Semaine',
    translation: '(week)',
    phonetic: '/səmɛn/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Je serai là la semaine prochaine.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Heure',
    translation: '(hour)',
    phonetic: '/œʁ/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ["Le vol dure une heure."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Quelle heure est-il ?',
    translation: '(what time is it?)',
    phonetic: '/kɛl œʁ ɛ til/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["Quelle heure est-il ? J'ai bientôt une réunion."],
    milestoneTags: ['onboarding'],
  },

  // ── Connectors (7) ─────────────────────────────────────────────
  {
    word: 'Et',
    translation: '(and)',
    phonetic: '/e/',
    category: 'connector',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ["J'ai un stylo et un cahier."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Mais',
    translation: '(but)',
    phonetic: '/mɛ/',
    category: 'connector',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['Je suis fatigué, mais je vais finir.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Parce que',
    translation: '(because)',
    phonetic: '/paʁs kə/',
    category: 'connector',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['Je suis resté parce qu\'il pleuvait.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Ou',
    translation: '(or)',
    phonetic: '/u/',
    category: 'connector',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['Vous voulez du thé ou du café ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Donc',
    translation: '(so/therefore)',
    phonetic: '/dɔ̃k/',
    category: 'connector',
    cefrLevel: 'A2',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['Il était tard, donc j\'ai pris un taxi.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Aussi',
    translation: '(also)',
    phonetic: '/osi/',
    category: 'connector',
    cefrLevel: 'A2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Je parle aussi anglais.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Puis',
    translation: '(then)',
    phonetic: '/pɥi/',
    category: 'connector',
    cefrLevel: 'A2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ["D'abord je mange, puis je vais au travail."],
    milestoneTags: ['onboarding'],
  },

  // ── Daily Essentials (12) ──────────────────────────────────────
  {
    word: 'Eau',
    translation: '(water)',
    phonetic: '/o/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ["Puis-je avoir de l'eau, s'il vous plaît ?"],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Nourriture',
    translation: '(food)',
    phonetic: '/nuʁityʁ/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['La nourriture ici est très bonne.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Argent',
    translation: '(money)',
    phonetic: '/aʁʒɑ̃/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Je dois retirer de l\'argent.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Maison',
    translation: '(house)',
    phonetic: '/mɛzɔ̃/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Ma maison est près du parc.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Rue',
    translation: '(street)',
    phonetic: '/ʁy/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Le magasin est dans la prochaine rue.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Voiture',
    translation: '(car)',
    phonetic: '/vwatyʁ/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Je vais au travail en voiture.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Téléphone',
    translation: '(phone)',
    phonetic: '/telefɔn/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Mon téléphone ne marche pas.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Grand',
    translation: '(big/tall)',
    phonetic: '/ɡʁɑ̃/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Cette chambre est très grande.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Petit',
    translation: '(small/short)',
    phonetic: '/pəti/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ["J'ai besoin d'un petit sac."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Bon',
    translation: '(good)',
    phonetic: '/bɔ̃/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ["C'est un bon restaurant."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Mauvais',
    translation: '(bad)',
    phonetic: '/movɛ/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ["Le temps est mauvais aujourd'hui."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Nouveau',
    translation: '(new)',
    phonetic: '/nuvo/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ["J'ai un nouveau travail."],
    milestoneTags: ['onboarding'],
  },

  // ── Common Expressions (6) ─────────────────────────────────────
  {
    word: 'Je ne comprends pas',
    translation: '(I do not understand)',
    phonetic: '/ʒə nə kɔ̃pʁɑ̃ pɑ/',
    category: 'expression',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Je ne comprends pas, pouvez-vous répéter ?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Je pense que',
    translation: '(I think that)',
    phonetic: '/ʒə pɑ̃s kə/',
    category: 'expression',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["Je pense que le musée est fermé aujourd'hui."],
    milestoneTags: ['onboarding'],
  },
  {
    word: "Je suis d'accord",
    translation: '(I agree)',
    phonetic: '/ʒə sɥi dakɔʁ/',
    category: 'expression',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ["Je suis d'accord, c'est une bonne idée."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Peut-être',
    translation: '(maybe)',
    phonetic: '/pø tɛtʁ/',
    category: 'expression',
    cefrLevel: 'A2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Peut-être que nous pouvons y aller demain.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Beaucoup',
    translation: '(a lot/very much)',
    phonetic: '/boku/',
    category: 'expression',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ["J'ai beaucoup de travail aujourd'hui."],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Très',
    translation: '(very)',
    phonetic: '/tʁɛ/',
    category: 'expression',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Ce café est très chaud.'],
    milestoneTags: ['onboarding'],
  },
];
