import type { AddWordInput } from '@/lib/word-bank/types';

/**
 * 85 Spanish words for B1-B2 learners.
 * Covers professional communication, nuanced verbs, opinions, business, and advanced daily vocabulary.
 */
export const SPANISH_INTERMEDIATE: AddWordInput[] = [
  // ── Professional Greetings & Introductions (8) ─────────────────
  {
    word: 'Se lo agradezco',
    translation: '(I appreciate it — formal)',
    phonetic: '/se lo aɣɾaˈðeθko/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Gracias por la información, se lo agradezco.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Espero con interés',
    translation: '(I look forward to)',
    phonetic: '/esˈpeɾo kon inteˈɾes/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Espero con interés nuestra próxima reunión.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Ha sido un placer',
    translation: '(it has been a pleasure)',
    phonetic: '/a ˈsiðo un plaˈθeɾ/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Ha sido un placer conocerle.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: '¿Cómo le ha ido?',
    translation: '(how have you been? — formal)',
    phonetic: '/ˈkomo le a ˈiðo/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Cuánto tiempo sin verle, ¿cómo le ha ido?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Permítame presentarme',
    translation: '(allow me to introduce myself)',
    phonetic: '/peɾˈmitame pɾesenˈtaɾme/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Permítame presentarme, soy el jefe de proyecto.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'En nombre del equipo',
    translation: '(on behalf of the team)',
    phonetic: '/en ˈnombɾe ðel eˈkipo/',
    category: 'greeting',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['En nombre del equipo, bienvenido.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Encantado de conocerle',
    translation: '(delighted to meet you — formal)',
    phonetic: '/enkanˈtaðo ðe konoˈθeɾle/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Encantado de conocerle, me han hablado mucho de usted.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Cuídese',
    translation: '(take care — formal)',
    phonetic: '/ˈkwiðese/',
    category: 'greeting',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Cuídese, y no dude en contactarme.'],
    milestoneTags: ['onboarding'],
  },

  // ── Business & Professional Questions (10) ─────────────────────
  {
    word: '¿Qué opina usted?',
    translation: '(what is your opinion?)',
    phonetic: '/ke oˈpina usˈteð/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Aquí está la propuesta, ¿qué opina usted?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: '¿Podría aclarar?',
    translation: '(could you clarify?)',
    phonetic: '/poˈðɾia aklaˈɾaɾ/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['¿Podría aclarar la fecha límite de esta tarea?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: '¿Sería posible?',
    translation: '(would it be possible?)',
    phonetic: '/seˈɾia poˈsiβle/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['¿Sería posible reprogramar la reunión?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: '¿Cuáles son los próximos pasos?',
    translation: '(what are the next steps?)',
    phonetic: '/ˈkwales son los ˈpɾoksimos ˈpasos/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Buena discusión — ¿cuáles son los próximos pasos?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: '¿Cómo abordaría usted?',
    translation: '(how would you approach?)',
    phonetic: '/ˈkomo aβoɾðaˈɾia usˈteð/',
    category: 'question',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['¿Cómo abordaría usted este problema?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: '¿Tiene alguna preocupación?',
    translation: '(do you have any concerns?)',
    phonetic: '/ˈtjene alˈɣuna pɾeokupaˈθjon/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Antes de continuar, ¿tiene alguna preocupación?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: '¿Hay algo más?',
    translation: '(is there anything else?)',
    phonetic: '/aj ˈalɣo mas/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['¿Hay algo más que necesite de mi parte?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: '¿Cuál es su disponibilidad?',
    translation: '(what is your availability?)',
    phonetic: '/kwal es su ðisponiβiliˈðað/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['¿Cuál es su disponibilidad la semana que viene?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: '¿Podría ampliar sobre?',
    translation: '(could you elaborate on?)',
    phonetic: '/poˈðɾia ampliˈaɾ soβɾe/',
    category: 'question',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['¿Podría ampliar sobre las cifras del presupuesto?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: '¿En qué estado se encuentra?',
    translation: '(what is the status of?)',
    phonetic: '/en ke esˈtaðo se enˈkwentɾa/',
    category: 'question',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['¿En qué estado se encuentra el contrato?'],
    milestoneTags: ['onboarding'],
  },

  // ── Advanced Verbs (14) ────────────────────────────────────────
  {
    word: 'Lograr',
    translation: '(to achieve)',
    phonetic: '/loˈɣɾaɾ/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Necesitamos lograr nuestros objetivos este trimestre.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Mejorar',
    translation: '(to improve)',
    phonetic: '/mexoˈɾaɾ/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['¿Cómo podemos mejorar el proceso?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Considerar',
    translation: '(to consider)',
    phonetic: '/konsideˈɾaɾ/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Deberíamos considerar todas las opciones.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Sugerir',
    translation: '(to suggest)',
    phonetic: '/suxeˈɾiɾ/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Sugiero que empecemos con el análisis de datos.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Gestionar',
    translation: '(to manage)',
    phonetic: '/xestjoˈnaɾ/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Ella gestiona un equipo de doce personas.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Requerir',
    translation: '(to require)',
    phonetic: '/rekeˈɾiɾ/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Este puesto requiere tres años de experiencia.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Proporcionar',
    translation: '(to provide)',
    phonetic: '/pɾopoɾθjoˈnaɾ/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Puedo proporcionar los documentos el viernes.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Desarrollar',
    translation: '(to develop)',
    phonetic: '/desaroˈʎaɾ/',
    category: 'verb',
    cefrLevel: 'B1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Estamos desarrollando una nueva línea de productos.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Negociar',
    translation: '(to negotiate)',
    phonetic: '/neɣoˈθjaɾ/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Necesitamos negociar los términos del contrato.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Implementar',
    translation: '(to implement)',
    phonetic: '/implemenˈtaɾ/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Implementaremos los cambios el próximo mes.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Analizar',
    translation: '(to analyze)',
    phonetic: '/analiˈθaɾ/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Déjeme analizar los datos antes de la reunión.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Resolver',
    translation: '(to resolve)',
    phonetic: '/resolˈβeɾ/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Necesitamos resolver este problema rápidamente.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Colaborar',
    translation: '(to collaborate)',
    phonetic: '/kolaβoˈɾaɾ/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Nuestros equipos colaboran en proyectos transversales.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Priorizar',
    translation: '(to prioritize)',
    phonetic: '/pɾjoɾiˈθaɾ/',
    category: 'verb',
    cefrLevel: 'B2',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Debemos priorizar las tareas más urgentes.'],
    milestoneTags: ['onboarding'],
  },

  // ── Polite / Diplomatic Phrases (7) ────────────────────────────
  {
    word: 'Entiendo su punto de vista',
    translation: '(I see your point)',
    phonetic: '/enˈtjendo su ˈpunto ðe ˈβista/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Entiendo su punto de vista, pero ¿ha considerado el coste?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Con todo respeto',
    translation: '(with all due respect)',
    phonetic: '/kon ˈtoðo resˈpeto/',
    category: 'polite',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Con todo respeto, no estoy de acuerdo con ese enfoque.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Me preguntaba si',
    translation: '(I was wondering if)',
    phonetic: '/me pɾeɣunˈtaβa si/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Me preguntaba si podría enviarme el informe.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Me temo que',
    translation: '(I am afraid that)',
    phonetic: '/me ˈtemo ke/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Me temo que no podemos cumplir ese plazo.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Que yo sepa',
    translation: '(as far as I know)',
    phonetic: '/ke ʝo ˈsepa/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Que yo sepa, el proyecto va bien.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: '¿Le importaría?',
    translation: '(would you mind?)',
    phonetic: '/le impoɾtaˈɾia/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['¿Le importaría cerrar la puerta?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Para ser sincero',
    translation: '(to be honest)',
    phonetic: '/paɾa seɾ sinˈθeɾo/',
    category: 'polite',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Para ser sincero, creo que necesitamos más tiempo.'],
    milestoneTags: ['onboarding'],
  },

  // ── Emergency / Travel (6) ─────────────────────────────────────
  {
    word: 'Necesito cancelar',
    translation: '(I need to cancel)',
    phonetic: '/neθeˈsito kanθeˈlaɾ/',
    category: 'emergency',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Necesito cancelar mi reserva.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Quiero presentar una queja',
    translation: '(I want to make a complaint)',
    phonetic: '/ˈkjeɾo pɾesenˈtaɾ una ˈkexa/',
    category: 'emergency',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Quiero presentar una queja sobre el servicio.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Seguro',
    translation: '(insurance)',
    phonetic: '/seˈɣuɾo/',
    category: 'emergency',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['¿Tiene seguro de viaje?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Cita',
    translation: '(appointment)',
    phonetic: '/ˈθita/',
    category: 'emergency',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Tengo una cita a las tres.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Receta',
    translation: '(prescription)',
    phonetic: '/reˈθeta/',
    category: 'emergency',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Necesito que me preparen esta receta en la farmacia.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Embajada',
    translation: '(embassy)',
    phonetic: '/embaˈxaða/',
    category: 'emergency',
    cefrLevel: 'B2',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Necesito contactar con mi embajada.'],
    milestoneTags: ['onboarding'],
  },

  // ── Time & Scheduling (8) ─────────────────────────────────────
  {
    word: 'Fecha límite',
    translation: '(deadline)',
    phonetic: '/ˈfetʃa ˈlimite/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['La fecha límite es el viernes que viene.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Horario',
    translation: '(schedule)',
    phonetic: '/oˈɾaɾjo/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Déjeme revisar mi horario.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Con antelación',
    translation: '(in advance)',
    phonetic: '/kon antelaˈθjon/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Avíseme con antelación, por favor.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Lo antes posible',
    translation: '(as soon as possible)',
    phonetic: '/lo ˈantes poˈsiβle/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Por favor, responda lo antes posible.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Mientras tanto',
    translation: '(meanwhile)',
    phonetic: '/ˈmjentɾas ˈtanto/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Mientras tanto, prepararé la presentación.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Finalmente',
    translation: '(eventually/finally)',
    phonetic: '/finalˈmente/',
    category: 'time',
    cefrLevel: 'B2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Finalmente encontraremos una solución.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Recientemente',
    translation: '(recently)',
    phonetic: '/reθjenteˈmente/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Recientemente me he mudado de apartamento.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'De ahora en adelante',
    translation: '(from now on)',
    phonetic: '/de aˈoɾa en aðeˈlante/',
    category: 'time',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['De ahora en adelante, las reuniones empiezan a las nueve.'],
    milestoneTags: ['onboarding'],
  },

  // ── Connectors & Discourse (8) ─────────────────────────────────
  {
    word: 'Sin embargo',
    translation: '(however)',
    phonetic: '/sin emˈbaɾɣo/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['El plan es bueno; sin embargo, el presupuesto es ajustado.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Por lo tanto',
    translation: '(therefore)',
    phonetic: '/poɾ lo ˈtanto/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Los datos son claros; por lo tanto, deberíamos avanzar.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Aunque',
    translation: '(although)',
    phonetic: '/ˈaunke/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['Aunque fue difícil, completamos el proyecto.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Además',
    translation: '(furthermore/in addition)',
    phonetic: '/aðeˈmas/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Además, necesitamos considerar el calendario.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Aparte de eso',
    translation: '(besides that)',
    phonetic: '/aˈpaɾte ðe ˈeso/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Aparte de eso, hemos conseguido nueva financiación.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Por otro lado',
    translation: '(on the other hand)',
    phonetic: '/poɾ ˈotɾo ˈlaðo/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Por otro lado, este enfoque ahorra tiempo.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Como resultado',
    translation: '(as a result)',
    phonetic: '/ˈkomo resulˈtaðo/',
    category: 'connector',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Las ventas cayeron; como resultado, ajustamos la estrategia.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'No obstante',
    translation: '(nevertheless)',
    phonetic: '/no oβsˈtante/',
    category: 'connector',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Era arriesgado; no obstante, decidimos invertir.'],
    milestoneTags: ['onboarding'],
  },

  // ── Daily / Professional Essentials (12) ───────────────────────
  {
    word: 'Presupuesto',
    translation: '(budget)',
    phonetic: '/pɾesuˈpwesto/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Debemos mantenernos dentro del presupuesto.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Retroalimentación',
    translation: '(feedback)',
    phonetic: '/retɾoalimentaˈθjon/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Agradecería su retroalimentación sobre este borrador.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Oportunidad',
    translation: '(opportunity)',
    phonetic: '/opoɾtuniˈðað/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Esta es una gran oportunidad de crecimiento.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Reto',
    translation: '(challenge)',
    phonetic: '/ˈreto/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['El mayor reto es el calendario ajustado.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Experiencia',
    translation: '(experience)',
    phonetic: '/ekspeˈɾjenθja/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Tengo cinco años de experiencia en marketing.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Eficiente',
    translation: '(efficient)',
    phonetic: '/efiˈθjente/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Necesitamos un flujo de trabajo más eficiente.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Disponible',
    translation: '(available)',
    phonetic: '/disponiˈβle/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Estoy disponible el martes por la tarde.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Responsable',
    translation: '(responsible)',
    phonetic: '/responsaˈβle/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Ella es responsable del equipo de marketing.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Significativo',
    translation: '(significant)',
    phonetic: '/siɣnifikaˈtiβo/',
    category: 'daily',
    cefrLevel: 'B2',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Ha habido una mejora significativa.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Adecuado',
    translation: '(appropriate)',
    phonetic: '/aðeˈkwaðo/',
    category: 'daily',
    cefrLevel: 'B2',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['¿Es este el momento adecuado para discutirlo?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Completo',
    translation: '(comprehensive/complete)',
    phonetic: '/komˈpleto/',
    category: 'daily',
    cefrLevel: 'B2',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Necesitamos una revisión completa del plan.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Fiable',
    translation: '(reliable)',
    phonetic: '/ˈfjaβle/',
    category: 'daily',
    cefrLevel: 'B1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Es la persona más fiable del equipo.'],
    milestoneTags: ['onboarding'],
  },

  // ── Expressions & Opinions (12) ────────────────────────────────
  {
    word: 'En mi opinión',
    translation: '(in my opinion)',
    phonetic: '/en mi opiˈnjon/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['En mi opinión, deberíamos esperar.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Depende de',
    translation: '(it depends on)',
    phonetic: '/deˈpende ðe/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Depende de la decisión del cliente.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Tiene sentido',
    translation: '(that makes sense)',
    phonetic: '/ˈtjene senˈtiðo/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Tiene sentido, sigamos adelante.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'No estoy seguro',
    translation: '(I am not sure)',
    phonetic: '/no esˈtoj seˈɣuɾo/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['No estoy seguro de la fecha exacta.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Resultó que',
    translation: '(it turned out that)',
    phonetic: '/resulˈto ke/',
    category: 'expression',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Resultó que el informe era incorrecto.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'De hecho',
    translation: '(as a matter of fact)',
    phonetic: '/de ˈetʃo/',
    category: 'expression',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['De hecho, ya he empezado.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Por ejemplo',
    translation: '(for instance)',
    phonetic: '/poɾ eˈxemplo/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Por ejemplo, podríamos reducir costes externalizando.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Básicamente',
    translation: '(basically)',
    phonetic: '/ˈbasikaˈmente/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Básicamente, necesitamos empezar de nuevo.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Obviamente',
    translation: '(obviously)',
    phonetic: '/ˈoβjamente/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Obviamente, el primer paso es recopilar datos.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Al parecer',
    translation: '(apparently)',
    phonetic: '/al paɾeˈθeɾ/',
    category: 'expression',
    cefrLevel: 'B2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Al parecer, la reunión se ha trasladado al jueves.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Al menos',
    translation: '(at least)',
    phonetic: '/al ˈmenos/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Tardará al menos dos semanas.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Más o menos',
    translation: '(more or less)',
    phonetic: '/mas o ˈmenos/',
    category: 'expression',
    cefrLevel: 'B1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['El proyecto va más o menos según lo previsto.'],
    milestoneTags: ['onboarding'],
  },
];
