import type { AddWordInput } from '@/lib/word-bank/types';

/**
 * 85 core Spanish words for A1-A2 learners.
 * Covers greetings, essential verbs, daily life, time, polite phrases, and survival vocabulary.
 */
export const SPANISH_BEGINNER: AddWordInput[] = [
  // ── Greetings & Introductions (10) ─────────────────────────────
  {
    word: 'Hola',
    translation: '(greeting)',
    phonetic: '/ˈola/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Hola, ¿cómo estás?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Adiós',
    translation: '(farewell)',
    phonetic: '/aˈðjos/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Adiós, ¡hasta mañana!'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Por favor',
    translation: '(please)',
    phonetic: '/poɾ faˈβoɾ/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Un café, por favor.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Gracias',
    translation: '(thank you)',
    phonetic: '/ˈɡɾaθjas/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Muchas gracias por tu ayuda.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Sí',
    translation: '(yes)',
    phonetic: '/si/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Sí, entiendo.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'No',
    translation: '(no)',
    phonetic: '/no/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['No, gracias.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Buenos días',
    translation: '(good morning)',
    phonetic: '/ˈbwenos ˈdias/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Buenos días a todos.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Buenas noches',
    translation: '(good night)',
    phonetic: '/ˈbwenas ˈnotʃes/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Buenas noches, que descanses.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Me llamo',
    translation: '(my name is)',
    phonetic: '/me ˈʎamo/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Me llamo Ana.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Mucho gusto',
    translation: '(nice to meet you)',
    phonetic: '/ˈmutʃo ˈɡusto/',
    category: 'greeting',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Mucho gusto, soy Carlos.'],
    milestoneTags: ['onboarding'],
  },

  // ── Common Questions (10) ──────────────────────────────────────
  {
    word: 'Qué',
    translation: '(what)',
    phonetic: '/ke/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['¿Qué es esto?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Dónde',
    translation: '(where)',
    phonetic: '/ˈdonde/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['¿Dónde está la estación?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Cuándo',
    translation: '(when)',
    phonetic: '/ˈkwando/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['¿Cuándo sale el autobús?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Cómo',
    translation: '(how)',
    phonetic: '/ˈkomo/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['¿Cómo estás hoy?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Por qué',
    translation: '(why)',
    phonetic: '/poɾ ˈke/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['¿Por qué está cerrada la tienda?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Quién',
    translation: '(who)',
    phonetic: '/kjen/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['¿Quién es tu profesor?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Cuánto cuesta',
    translation: '(how much does it cost)',
    phonetic: '/ˈkwanto ˈkwesta/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['¿Cuánto cuesta esto?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: '¿Habla inglés?',
    translation: '(do you speak English?)',
    phonetic: '/ˈaβla iŋˈɡles/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Disculpe, ¿habla inglés?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: '¿Puede ayudarme?',
    translation: '(can you help me?)',
    phonetic: '/ˈpweðe aʝuˈðaɾme/',
    category: 'question',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['¿Puede ayudarme a encontrar el hotel?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Cuál',
    translation: '(which)',
    phonetic: '/kwal/',
    category: 'question',
    cefrLevel: 'A2',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['¿Cuál prefieres?'],
    milestoneTags: ['onboarding'],
  },

  // ── Essential Verbs (15) ───────────────────────────────────────
  {
    word: 'Ser',
    translation: '(to be — permanent)',
    phonetic: '/seɾ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Soy estudiante.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Estar',
    translation: '(to be — state/location)',
    phonetic: '/esˈtaɾ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Estoy en la oficina.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Tener',
    translation: '(to have)',
    phonetic: '/teˈneɾ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Tengo dos hermanos.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Ir',
    translation: '(to go)',
    phonetic: '/iɾ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Voy al trabajo cada día.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Querer',
    translation: '(to want)',
    phonetic: '/keˈɾeɾ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Quiero un vaso de agua.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Necesitar',
    translation: '(to need)',
    phonetic: '/neθesiˈtaɾ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Necesito ver a un médico.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Gustar',
    translation: '(to like)',
    phonetic: '/ɡusˈtaɾ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Me gusta el café por la mañana.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Saber',
    translation: '(to know — facts)',
    phonetic: '/saˈβeɾ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Sé dónde está.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Poder',
    translation: '(to be able to)',
    phonetic: '/poˈðeɾ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['¿Puedo sentarme aquí?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Venir',
    translation: '(to come)',
    phonetic: '/beˈniɾ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Ven aquí, por favor.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Comer',
    translation: '(to eat)',
    phonetic: '/koˈmeɾ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Como el desayuno a las siete.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Beber',
    translation: '(to drink)',
    phonetic: '/beˈβeɾ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Bebo agua todos los días.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Hablar',
    translation: '(to speak)',
    phonetic: '/aˈβlaɾ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Hablo un poco de español.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Entender',
    translation: '(to understand)',
    phonetic: '/entenˈdeɾ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Entiendo la pregunta.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Vivir',
    translation: '(to live)',
    phonetic: '/biˈβiɾ/',
    category: 'verb',
    cefrLevel: 'A1',
    partOfSpeech: 'verb',
    source: 'lesson',
    exampleSentences: ['Vivo en esta ciudad.'],
    milestoneTags: ['onboarding'],
  },

  // ── Polite Phrases (8) ─────────────────────────────────────────
  {
    word: 'Disculpe',
    translation: '(excuse me — formal)',
    phonetic: '/disˈkulpe/',
    category: 'polite',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Disculpe, ¿dónde está la salida?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Lo siento',
    translation: '(I am sorry)',
    phonetic: '/lo ˈsjento/',
    category: 'polite',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Lo siento, no le escuché.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'De nada',
    translation: '(you are welcome)',
    phonetic: '/de ˈnaða/',
    category: 'polite',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['De nada, fue un placer.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: '¿Puede repetir?',
    translation: '(can you repeat?)',
    phonetic: '/ˈpweðe repeˈtiɾ/',
    category: 'polite',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['¿Puede repetir más despacio?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Me gustaría',
    translation: '(I would like)',
    phonetic: '/me ɡustaˈɾia/',
    category: 'polite',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Me gustaría una mesa para dos.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: '¿Puedo?',
    translation: '(may I?)',
    phonetic: '/ˈpweðo/',
    category: 'polite',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['¿Puedo sentarme aquí?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'No hay problema',
    translation: '(no problem)',
    phonetic: '/no aj pɾoˈβlema/',
    category: 'polite',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['No hay problema, tómate tu tiempo.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Por supuesto',
    translation: '(of course)',
    phonetic: '/poɾ suˈpwesto/',
    category: 'polite',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Por supuesto, puedo ayudarte.'],
    milestoneTags: ['onboarding'],
  },

  // ── Emergency / Survival (7) ───────────────────────────────────
  {
    word: 'Ayuda',
    translation: '(help)',
    phonetic: '/aˈʝuða/',
    category: 'emergency',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['¡Necesito ayuda!'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Hospital',
    translation: '(hospital)',
    phonetic: '/ospiˈtal/',
    category: 'emergency',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['¿Dónde está el hospital más cercano?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Policía',
    translation: '(police)',
    phonetic: '/poliˈθia/',
    category: 'emergency',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Llame a la policía, por favor.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Baño',
    translation: '(bathroom)',
    phonetic: '/ˈbaɲo/',
    category: 'emergency',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['¿Dónde está el baño?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Estoy perdido',
    translation: '(I am lost)',
    phonetic: '/esˈtoj peɾˈðiðo/',
    category: 'emergency',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Estoy perdido, ¿puede mostrarme en el mapa?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'No me siento bien',
    translation: '(I do not feel well)',
    phonetic: '/no me ˈsjento βjen/',
    category: 'emergency',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['No me siento bien, necesito sentarme.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Emergencia',
    translation: '(emergency)',
    phonetic: '/emeɾˈxenθja/',
    category: 'emergency',
    cefrLevel: 'A2',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Es una emergencia, por favor, dese prisa.'],
    milestoneTags: ['onboarding'],
  },

  // ── Time & Numbers (10) ────────────────────────────────────────
  {
    word: 'Hoy',
    translation: '(today)',
    phonetic: '/oj/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Hoy tengo una reunión.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Mañana',
    translation: '(tomorrow)',
    phonetic: '/maˈɲana/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Te llamaré mañana.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Ayer',
    translation: '(yesterday)',
    phonetic: '/aˈʝeɾ/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Llegué ayer.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Ahora',
    translation: '(now)',
    phonetic: '/aˈoɾa/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Estoy listo ahora.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Más tarde',
    translation: '(later)',
    phonetic: '/mas ˈtaɾðe/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Lo haré más tarde.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Mañana (la)',
    translation: '(morning)',
    phonetic: '/maˈɲana/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Hago ejercicio cada mañana.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Noche',
    translation: '(night)',
    phonetic: '/ˈnotʃe/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['El restaurante está abierto por la noche.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Semana',
    translation: '(week)',
    phonetic: '/seˈmana/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Estaré allí la próxima semana.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Hora',
    translation: '(hour)',
    phonetic: '/ˈoɾa/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['El vuelo dura una hora.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: '¿Qué hora es?',
    translation: '(what time is it?)',
    phonetic: '/ke ˈoɾa es/',
    category: 'time',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['¿Qué hora es? Tengo una reunión pronto.'],
    milestoneTags: ['onboarding'],
  },

  // ── Connectors (7) ─────────────────────────────────────────────
  {
    word: 'Y',
    translation: '(and)',
    phonetic: '/i/',
    category: 'connector',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['Tengo un bolígrafo y un cuaderno.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Pero',
    translation: '(but)',
    phonetic: '/ˈpeɾo/',
    category: 'connector',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['Estoy cansado, pero voy a terminar.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Porque',
    translation: '(because)',
    phonetic: '/ˈpoɾke/',
    category: 'connector',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['Me quedé en casa porque llovía.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'O',
    translation: '(or)',
    phonetic: '/o/',
    category: 'connector',
    cefrLevel: 'A1',
    partOfSpeech: 'other',
    source: 'lesson',
    exampleSentences: ['¿Quieres té o café?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Entonces',
    translation: '(so/then)',
    phonetic: '/enˈtonθes/',
    category: 'connector',
    cefrLevel: 'A2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Era tarde, entonces tomé un taxi.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'También',
    translation: '(also)',
    phonetic: '/tamˈbjen/',
    category: 'connector',
    cefrLevel: 'A2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['También hablo francés.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Luego',
    translation: '(then/afterwards)',
    phonetic: '/ˈlweɣo/',
    category: 'connector',
    cefrLevel: 'A2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Primero como, luego voy al trabajo.'],
    milestoneTags: ['onboarding'],
  },

  // ── Daily Essentials (12) ──────────────────────────────────────
  {
    word: 'Agua',
    translation: '(water)',
    phonetic: '/ˈaɣwa/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['¿Puedo tener un poco de agua, por favor?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Comida',
    translation: '(food)',
    phonetic: '/koˈmiða/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['La comida aquí es muy buena.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Dinero',
    translation: '(money)',
    phonetic: '/diˈneɾo/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Necesito encontrar un cajero para sacar dinero.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Casa',
    translation: '(house)',
    phonetic: '/ˈkasa/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Mi casa está cerca del parque.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Calle',
    translation: '(street)',
    phonetic: '/ˈkaʎe/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['La tienda está en la próxima calle.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Coche',
    translation: '(car)',
    phonetic: '/ˈkotʃe/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Voy al trabajo en coche.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Teléfono',
    translation: '(phone)',
    phonetic: '/teˈlefono/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'noun',
    source: 'lesson',
    exampleSentences: ['Mi teléfono no funciona.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Grande',
    translation: '(big)',
    phonetic: '/ˈɡɾande/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Esta habitación es muy grande.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Pequeño',
    translation: '(small)',
    phonetic: '/peˈkeɲo/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Necesito una bolsa pequeña.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Bueno',
    translation: '(good)',
    phonetic: '/ˈbweno/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Este es un buen restaurante.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Malo',
    translation: '(bad)',
    phonetic: '/ˈmalo/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['El tiempo está malo hoy.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Nuevo',
    translation: '(new)',
    phonetic: '/ˈnweβo/',
    category: 'daily',
    cefrLevel: 'A1',
    partOfSpeech: 'adjective',
    source: 'lesson',
    exampleSentences: ['Tengo un trabajo nuevo.'],
    milestoneTags: ['onboarding'],
  },

  // ── Common Expressions (6) ─────────────────────────────────────
  {
    word: 'No entiendo',
    translation: '(I do not understand)',
    phonetic: '/no enˈtjendo/',
    category: 'expression',
    cefrLevel: 'A1',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['No entiendo, ¿puede decirlo otra vez?'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Creo que',
    translation: '(I think that)',
    phonetic: '/ˈkɾeo ke/',
    category: 'expression',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Creo que el museo está cerrado hoy.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Estoy de acuerdo',
    translation: '(I agree)',
    phonetic: '/esˈtoj de aˈkweɾðo/',
    category: 'expression',
    cefrLevel: 'A2',
    partOfSpeech: 'phrase',
    source: 'lesson',
    exampleSentences: ['Estoy de acuerdo, es una buena idea.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Quizás',
    translation: '(maybe)',
    phonetic: '/kiˈθas/',
    category: 'expression',
    cefrLevel: 'A2',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Quizás podemos ir mañana.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Mucho',
    translation: '(a lot)',
    phonetic: '/ˈmutʃo/',
    category: 'expression',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Tengo mucho trabajo hoy.'],
    milestoneTags: ['onboarding'],
  },
  {
    word: 'Muy',
    translation: '(very)',
    phonetic: '/muj/',
    category: 'expression',
    cefrLevel: 'A1',
    partOfSpeech: 'adverb',
    source: 'lesson',
    exampleSentences: ['Este café está muy caliente.'],
    milestoneTags: ['onboarding'],
  },
];
