/**
 * AI-Powered Reading Library
 *
 * Personalized lecture recommendations generated by AI based on the user's
 * learning profile, motivation, and current vocabulary level. Refreshed weekly.
 *
 * Flow: Library → About Lecture → Teleprompter
 *
 * Features:
 * - AI-curated featured carousel (most important this week)
 * - Dynamic category filtering
 * - Recommendation reasons shown per lecture
 * - Pull-to-refresh for new recommendations
 * - Loading state on first generation
 */

import React, { useState, useCallback, useRef, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Image,
  Dimensions,
  StatusBar,
  FlatList,
  ActivityIndicator,
  RefreshControl,
  NativeScrollEvent,
  NativeSyntheticEvent,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import Animated, {
  FadeIn,
  FadeInDown,
  FadeInRight,
} from 'react-native-reanimated';
import { useRouter } from 'expo-router';
import * as Haptics from 'expo-haptics';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { colors, spacing, borderRadius, typography } from '@/constants/designSystem';
import { BackButton } from '@/components/ui/BackButton';
import { useAuth } from '@/hooks/useAuth';
import { generateLibraryRecommendations, type LibraryLecture } from '@/lib/ai/libraryGenerator';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const FEATURED_CARD_WIDTH = SCREEN_WIDTH - spacing.xl * 2;
const FEATURED_CARD_HEIGHT = 180;

export default function LibraryScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { user } = useAuth();
  const [selectedCategory, setSelectedCategory] = useState('All');
  const [activeCarouselIndex, setActiveCarouselIndex] = useState(0);
  const carouselRef = useRef<FlatList>(null);

  const [lectures, setLectures] = useState<LibraryLecture[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Load AI recommendations
  const loadRecommendations = useCallback(async (forceRefresh = false) => {
    if (!user?.id) return;
    setError(null);
    try {
      const results = await generateLibraryRecommendations(user.id, forceRefresh);
      if (results.length === 0) {
        setError('Could not generate recommendations. Check your learning path.');
      }
      setLectures(results);
    } catch (err: any) {
      setError(err.message || 'Failed to load recommendations');
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [user?.id]);

  useEffect(() => {
    loadRecommendations();
  }, [loadRecommendations]);

  const handleRefresh = useCallback(() => {
    setRefreshing(true);
    loadRecommendations(true);
  }, [loadRecommendations]);

  // Derived data
  const featuredLectures = lectures.filter(l => l.featured);
  const allLectures = lectures.filter(l => !l.featured);

  // Extract categories dynamically from AI results
  const categories = ['All', ...Array.from(new Set(lectures.map(l => l.category)))];

  const filteredLectures = selectedCategory === 'All'
    ? allLectures
    : allLectures.filter(l => l.category === selectedCategory);

  const handleBack = () => {
    router.back();
  };

  const handleStoryPress = useCallback((lecture: LibraryLecture) => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    router.push({
      pathname: '/about-lecture',
      params: {
        id: lecture.id,
        title: lecture.title,
        subtitle: lecture.subtitle,
        category: lecture.category,
        difficulty: lecture.difficulty,
        duration: lecture.duration,
        wordCount: lecture.wordCount.toString(),
        imageUrl: lecture.imageUrl,
      },
    });
  }, [router]);

  const handleCategoryPress = useCallback((category: string) => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    setSelectedCategory(category);
  }, []);

  const handleCarouselScroll = useCallback((event: NativeSyntheticEvent<NativeScrollEvent>) => {
    const offsetX = event.nativeEvent.contentOffset.x;
    const index = Math.round(offsetX / (FEATURED_CARD_WIDTH + spacing.md));
    if (index !== activeCarouselIndex && index >= 0 && index < featuredLectures.length) {
      setActiveCarouselIndex(index);
    }
  }, [activeCarouselIndex, featuredLectures.length]);

  const getDifficultyColor = (difficulty: string) => {
    switch (difficulty) {
      case 'beginner': return colors.success.DEFAULT;
      case 'intermediate': return colors.warning.DEFAULT;
      case 'advanced': return colors.accent.orange;
      default: return colors.text.tertiary;
    }
  };

  // Render featured card for carousel
  const renderFeaturedCard = useCallback(({ item }: { item: LibraryLecture }) => (
    <TouchableOpacity
      onPress={() => handleStoryPress(item)}
      activeOpacity={0.9}
      style={styles.featuredCard}
    >
      <Image
        source={{ uri: item.imageUrl }}
        style={styles.featuredImage}
        resizeMode="cover"
      />
      <LinearGradient
        colors={['transparent', 'rgba(0,0,0,0.6)', 'rgba(0,0,0,0.9)']}
        locations={[0, 0.5, 1]}
        style={styles.featuredGradient}
      >
        <View style={styles.featuredContent}>
          <View style={styles.featuredBadgeRow}>
            <View style={[styles.difficultyBadge, { backgroundColor: getDifficultyColor(item.difficulty) + '30' }]}>
              <Text style={[styles.difficultyText, { color: getDifficultyColor(item.difficulty) }]}>
                {item.difficulty}
              </Text>
            </View>
            <Text style={styles.featuredDuration}>{item.duration}</Text>
          </View>
          <Text style={styles.featuredTitle}>{item.title}</Text>
          <Text style={styles.featuredSubtitle}>{item.subtitle}</Text>
          {item.reason && (
            <Text style={styles.reasonText} numberOfLines={1}>{item.reason}</Text>
          )}
        </View>
      </LinearGradient>
    </TouchableOpacity>
  ), [handleStoryPress, getDifficultyColor]);

  // ═══ LOADING STATE ═══
  if (loading) {
    return (
      <View style={styles.container}>
        <StatusBar barStyle="light-content" />
        <LinearGradient
          colors={[colors.background.primary, colors.background.secondary, '#1A1F3A']}
          style={StyleSheet.absoluteFill}
        />
        <Animated.View
          entering={FadeIn.duration(400)}
          style={[styles.header, { paddingTop: insets.top + spacing.md }]}
        >
          <BackButton onPress={handleBack} />
        </Animated.View>
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color={colors.primary.DEFAULT} />
          <Text style={styles.loadingText}>Curating your reading library...</Text>
          <Text style={styles.loadingSubtext}>Personalizing recommendations for you</Text>
        </View>
      </View>
    );
  }

  // ═══ ERROR STATE ═══
  if (error && lectures.length === 0) {
    return (
      <View style={styles.container}>
        <StatusBar barStyle="light-content" />
        <LinearGradient
          colors={[colors.background.primary, colors.background.secondary, '#1A1F3A']}
          style={StyleSheet.absoluteFill}
        />
        <Animated.View
          entering={FadeIn.duration(400)}
          style={[styles.header, { paddingTop: insets.top + spacing.md }]}
        >
          <BackButton onPress={handleBack} />
        </Animated.View>
        <View style={styles.loadingContainer}>
          <Ionicons name="alert-circle-outline" size={48} color={colors.text.tertiary} />
          <Text style={styles.loadingText}>{error}</Text>
          <TouchableOpacity style={styles.retryButton} onPress={() => { setLoading(true); loadRecommendations(true); }}>
            <Text style={styles.retryText}>Try Again</Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <StatusBar barStyle="light-content" />

      {/* Full-screen gradient background */}
      <LinearGradient
        colors={[colors.background.primary, colors.background.secondary, '#1A1F3A']}
        style={StyleSheet.absoluteFill}
      />

      {/* Header */}
      <Animated.View
        entering={FadeIn.duration(400)}
        style={[styles.header, { paddingTop: insets.top + spacing.md }]}
      >
        <BackButton onPress={handleBack} />
      </Animated.View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={handleRefresh}
            tintColor={colors.primary.DEFAULT}
          />
        }
      >
        {/* Title Section */}
        <Animated.View entering={FadeInDown.delay(100).duration(400)} style={styles.titleSection}>
          <Text style={styles.title}>Library</Text>
          <Text style={styles.subtitle}>AI-curated lectures for your goals</Text>
        </Animated.View>

        {/* Featured Carousel Section */}
        {featuredLectures.length > 0 && (
          <Animated.View entering={FadeInDown.delay(150).duration(400)} style={styles.carouselSection}>
            <Text style={styles.sectionLabel}>Recommended This Week</Text>

            <FlatList
              ref={carouselRef}
              data={featuredLectures}
              renderItem={renderFeaturedCard}
              keyExtractor={(item) => item.id}
              horizontal
              showsHorizontalScrollIndicator={false}
              snapToInterval={FEATURED_CARD_WIDTH + spacing.md}
              snapToAlignment="start"
              decelerationRate="fast"
              contentContainerStyle={styles.carouselContent}
              onScroll={handleCarouselScroll}
              scrollEventThrottle={16}
            />

            {/* Pagination Dots */}
            <View style={styles.paginationContainer}>
              {featuredLectures.map((_, index) => (
                <View
                  key={index}
                  style={[
                    styles.paginationDot,
                    index === activeCarouselIndex && styles.paginationDotActive,
                  ]}
                />
              ))}
            </View>
          </Animated.View>
        )}

        {/* Category Filter */}
        {categories.length > 1 && (
          <Animated.View entering={FadeInDown.delay(200).duration(400)}>
            <ScrollView
              horizontal
              showsHorizontalScrollIndicator={false}
              contentContainerStyle={styles.categoriesContainer}
            >
              {categories.map((category) => (
                <TouchableOpacity
                  key={category}
                  onPress={() => handleCategoryPress(category)}
                  style={[
                    styles.categoryPill,
                    selectedCategory === category && styles.categoryPillActive,
                  ]}
                  activeOpacity={0.8}
                >
                  <Text
                    style={[
                      styles.categoryText,
                      selectedCategory === category && styles.categoryTextActive,
                    ]}
                  >
                    {category}
                  </Text>
                </TouchableOpacity>
              ))}
            </ScrollView>
          </Animated.View>
        )}

        {/* Lectures List */}
        <Animated.View entering={FadeInDown.delay(250).duration(400)} style={styles.storiesSection}>
          <Text style={styles.sectionLabel}>
            {selectedCategory === 'All' ? 'All Lectures' : selectedCategory}
          </Text>

          {filteredLectures.length === 0 ? (
            <View style={styles.emptyState}>
              <Text style={styles.emptyText}>No lectures in this category</Text>
            </View>
          ) : (
            filteredLectures.map((lecture, index) => (
              <Animated.View
                key={lecture.id}
                entering={FadeInRight.delay(300 + index * 50).duration(300)}
              >
                <TouchableOpacity
                  onPress={() => handleStoryPress(lecture)}
                  activeOpacity={0.9}
                  style={styles.storyCard}
                >
                  <Image
                    source={{ uri: lecture.imageUrl }}
                    style={styles.storyImage}
                    resizeMode="cover"
                  />
                  <View style={styles.storyContent}>
                    <View style={styles.storyHeader}>
                      <Text style={styles.storyCategory}>{lecture.category}</Text>
                      <View style={[styles.difficultyDot, { backgroundColor: getDifficultyColor(lecture.difficulty) }]} />
                    </View>
                    <Text style={styles.storyTitle} numberOfLines={1}>{lecture.title}</Text>
                    <Text style={styles.storySubtitle} numberOfLines={1}>{lecture.subtitle}</Text>
                    <View style={styles.storyFooter}>
                      <Text style={styles.storyMeta}>{lecture.duration} · {lecture.wordCount} words</Text>
                    </View>
                  </View>
                  <View style={styles.storyArrow}>
                    <Text style={styles.arrowText}>›</Text>
                  </View>
                </TouchableOpacity>
              </Animated.View>
            ))
          )}
        </Animated.View>

        {/* Bottom Spacer */}
        <View style={{ height: insets.bottom + spacing.xl }} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  header: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.sm,
    zIndex: 10,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: spacing.xl,
  },

  // Loading
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
    gap: spacing.md,
  },
  loadingText: {
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    color: colors.text.secondary,
    textAlign: 'center',
  },
  loadingSubtext: {
    fontSize: typography.fontSize.sm,
    color: colors.text.tertiary,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: spacing.md,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  retryText: {
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    color: colors.primary.DEFAULT,
  },

  // Title Section
  titleSection: {
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.lg,
  },
  title: {
    fontSize: typography.fontSize['4xl'],
    fontWeight: typography.fontWeight.bold,
    color: colors.text.primary,
    marginBottom: spacing.xs,
  },
  subtitle: {
    fontSize: typography.fontSize.base,
    color: colors.text.tertiary,
  },

  // Carousel Section
  carouselSection: {
    marginBottom: spacing.lg,
  },
  carouselContent: {
    paddingHorizontal: spacing.lg,
  },
  featuredCard: {
    width: FEATURED_CARD_WIDTH,
    height: FEATURED_CARD_HEIGHT,
    borderRadius: borderRadius.xl,
    overflow: 'hidden',
    marginRight: spacing.md,
    backgroundColor: colors.background.card,
  },
  featuredImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  featuredGradient: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    padding: spacing.lg,
  },
  featuredContent: {},
  featuredBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  difficultyBadge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: borderRadius.sm,
  },
  difficultyText: {
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.semibold,
    textTransform: 'capitalize',
  },
  featuredDuration: {
    fontSize: typography.fontSize.xs,
    color: colors.text.secondary,
  },
  featuredTitle: {
    fontSize: typography.fontSize.xl,
    fontWeight: typography.fontWeight.bold,
    color: colors.text.primary,
    marginBottom: 2,
  },
  featuredSubtitle: {
    fontSize: typography.fontSize.sm,
    color: colors.text.secondary,
  },
  reasonText: {
    fontSize: typography.fontSize.xs,
    color: colors.primary.light || colors.primary.DEFAULT,
    marginTop: 4,
    fontStyle: 'italic',
  },

  // Pagination
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: spacing.md,
    gap: spacing.sm,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  paginationDotActive: {
    backgroundColor: colors.primary.DEFAULT,
    width: 24,
  },

  // Section Labels
  sectionLabel: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
    color: colors.text.tertiary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: spacing.md,
    paddingHorizontal: spacing.lg,
  },

  // Categories
  categoriesContainer: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.lg,
    gap: spacing.sm,
  },
  categoryPill: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.full,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    marginRight: spacing.sm,
  },
  categoryPillActive: {
    backgroundColor: colors.primary.DEFAULT,
    borderColor: colors.primary.DEFAULT,
  },
  categoryText: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    color: colors.text.tertiary,
  },
  categoryTextActive: {
    color: colors.text.primary,
    fontWeight: typography.fontWeight.semibold,
  },

  // Stories Section
  storiesSection: {
    marginBottom: spacing.lg,
  },
  storyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: borderRadius.lg,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.md,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    position: 'relative',
  },
  storyImage: {
    width: 80,
    height: 80,
    backgroundColor: colors.background.card,
  },
  storyContent: {
    flex: 1,
    padding: spacing.md,
  },
  storyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  storyCategory: {
    fontSize: typography.fontSize.xs,
    color: colors.text.tertiary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  difficultyDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  storyTitle: {
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    color: colors.text.primary,
    marginBottom: 2,
  },
  storySubtitle: {
    fontSize: typography.fontSize.sm,
    color: colors.text.tertiary,
    marginBottom: spacing.xs,
  },
  storyFooter: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  storyMeta: {
    fontSize: typography.fontSize.xs,
    color: colors.text.disabled,
  },
  storyArrow: {
    paddingHorizontal: spacing.md,
  },
  arrowText: {
    fontSize: 24,
    color: colors.text.tertiary,
    fontWeight: typography.fontWeight.light,
  },

  // Empty State
  emptyState: {
    paddingVertical: spacing.xl,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: typography.fontSize.base,
    color: colors.text.tertiary,
  },
});
