/**
 * Anthropic Claude API Client for Vox Language App
 *
 * This module provides a robust interface to Anthropic's Claude API,
 * with retry logic, error handling, and typed response parsing for
 * learning path planning and orchestration.
 *
 * In the Claude + Gemini orchestration architecture, Claude acts as the
 * supervisor (strategic planning, validation, quality control) while
 * Gemini Flash acts as the worker (bulk content generation).
 */

import Anthropic from '@anthropic-ai/sdk';

// ============================================================================
// TYPE DEFINITIONS
// ============================================================================

/**
 * User's learning profile used for generating personalized learning paths.
 * This is the primary input for Claude's strategic planning.
 */
export interface UserLearningProfile {
  /** User's native/fluent language (e.g., 'en', 'es') */
  nativeLanguage: string;
  /** Target language being learned (e.g., 'es', 'fr', 'de') */
  targetLanguage: string;
  /** Current CEFR proficiency level */
  currentLevel: 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';
  /** User's specific learning goals */
  learningGoals: string[];
  /** User's interests for content personalization */
  interests: string[];
  /** Daily available practice time in minutes */
  dailyTimeMinutes: number;
  /** Optional: User's motivation for learning */
  motivation?: string;
  /** Optional: User's timeline (e.g., '3_months', '6_months') */
  timeline?: string;
}

/**
 * Brief for a single stair/step in the learning path.
 * Claude generates these briefs, which Gemini then uses to generate content.
 */
export interface StairBrief {
  /** Unique identifier for the stair */
  id: string;
  /** Position in the learning path (1-indexed) */
  position: number;
  /** Thematic focus (e.g., 'Greetings', 'Food', 'Travel') */
  theme: string;
  /** Target CEFR level for this stair */
  cefrLevel: string;
  /** Focus vocabulary words/phrases to include */
  vocabularyFocus: string[];
  /** Grammar patterns to practice */
  grammarPatterns: string[];
  /** Communication goals for this stair */
  communicativeGoals: string[];
  /** Constraints for content generation */
  constraints: {
    /** Word frequency band range (e.g., [1, 3000] for top 3000 words) */
    wordFrequencyBand: [number, number];
    /** Maximum sentence length in words */
    maxSentenceLength: number;
    /** Topics to avoid in generated content */
    avoidTopics: string[];
  };
}

/**
 * Complete learning path plan generated by Claude.
 * Contains strategic structure and briefs for Gemini to execute.
 */
export interface LearningPathPlan {
  /** User ID this plan is for */
  userId: string;
  /** Total number of stairs in the path */
  totalStairs: number;
  /** Estimated duration to complete (e.g., '4 weeks', '2 months') */
  estimatedDuration: string;
  /** Array of stair briefs for content generation */
  stairs: StairBrief[];
  /** Description of the progression logic used */
  progressionLogic: string;
  /** Metadata about generation */
  metadata?: {
    generatedAt: string;
    modelVersion: string;
  };
}

// ============================================================================
// CONFIGURATION
// ============================================================================

const CLAUDE_CONFIG = {
  /** Default model - Claude Opus 4.5 for highest quality strategic planning */
  model: process.env.CLAUDE_MODEL || 'claude-opus-4-5-20251101',
  /** Maximum tokens for response */
  maxTokens: 4096,
  /** Temperature for controlled creativity */
  temperature: 0.7,
};

const RETRY_CONFIG = {
  maxAttempts: 3,
  baseDelayMs: 1000,
  maxDelayMs: 10000,
};

// ============================================================================
// ERROR HANDLING
// ============================================================================

/**
 * Custom error class for Claude API errors.
 * Includes information about whether the error is retryable.
 */
export class ClaudeError extends Error {
  constructor(
    message: string,
    public code: string,
    public retryable: boolean
  ) {
    super(message);
    this.name = 'ClaudeError';
  }
}

/**
 * Determines if an error is retryable based on its type.
 */
function isRetryableError(error: any): boolean {
  // Network errors
  if (error.code === 'NETWORK_ERROR' || error.code === 'ENOTFOUND') {
    return true;
  }

  // Rate limiting (429)
  if (error.status === 429) {
    return true;
  }

  // Server errors (5xx)
  if (error.status >= 500 && error.status < 600) {
    return true;
  }

  // Timeout errors
  if (error.code === 'ETIMEDOUT' || error.code === 'TIMEOUT') {
    return true;
  }

  // Anthropic-specific overload errors
  if (error.error?.type === 'overloaded_error') {
    return true;
  }

  return false;
}

/**
 * Calculates exponential backoff delay with jitter.
 */
function calculateDelay(attempt: number, isRateLimit: boolean = false): number {
  const baseDelay = isRateLimit
    ? RETRY_CONFIG.baseDelayMs * 3 // Longer delay for rate limits
    : RETRY_CONFIG.baseDelayMs;

  const exponentialDelay = baseDelay * Math.pow(2, attempt);
  const jitter = Math.random() * 1000;

  return Math.min(exponentialDelay + jitter, RETRY_CONFIG.maxDelayMs);
}

/**
 * Sleep utility for retry delays.
 */
function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

// ============================================================================
// CLIENT INITIALIZATION
// ============================================================================

let anthropicClient: Anthropic | null = null;

/**
 * Checks if the Anthropic API key is configured.
 * Returns true if the key is available, false otherwise.
 */
export function isClaudeAvailable(): boolean {
  return !!process.env.ANTHROPIC_API_KEY;
}

/**
 * Initializes the Anthropic client.
 * Returns null if API key is not configured (graceful fallback).
 */
function getClient(): Anthropic | null {
  if (anthropicClient) {
    return anthropicClient;
  }

  const apiKey = process.env.ANTHROPIC_API_KEY;

  if (!apiKey) {
    console.warn(
      '[ClaudeClient] ANTHROPIC_API_KEY not configured. ' +
        'Claude features will be disabled, falling back to Gemini-only mode.'
    );
    return null;
  }

  anthropicClient = new Anthropic({
    apiKey,
  });

  return anthropicClient;
}

// ============================================================================
// CORE GENERATION FUNCTIONS
// ============================================================================

/**
 * Sends a prompt to Claude and returns the raw text response.
 * Includes retry logic with exponential backoff for transient failures.
 *
 * @param prompt - The prompt to send to Claude
 * @param systemPrompt - Optional system prompt for context
 * @returns The raw text response from Claude, or null if Claude is unavailable
 * @throws {ClaudeError} If all retry attempts fail or a non-retryable error occurs
 */
export async function generateWithClaude(
  prompt: string,
  systemPrompt?: string
): Promise<string | null> {
  const client = getClient();

  if (!client) {
    // Graceful fallback - Claude not available
    return null;
  }

  let lastError: any;

  for (let attempt = 0; attempt < RETRY_CONFIG.maxAttempts; attempt++) {
    try {
      const message = await client.messages.create({
        model: CLAUDE_CONFIG.model,
        max_tokens: CLAUDE_CONFIG.maxTokens,
        ...(systemPrompt && { system: systemPrompt }),
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
      });

      // Extract text from the response
      const textBlock = message.content.find(block => block.type === 'text');
      if (!textBlock || textBlock.type !== 'text') {
        throw new ClaudeError(
          'Claude returned a response without text content',
          'EMPTY_RESPONSE',
          true
        );
      }

      return textBlock.text;
    } catch (error: any) {
      lastError = error;

      const isRetryable = isRetryableError(error);
      const isRateLimit = error.status === 429;

      // If not retryable or last attempt, throw
      if (!isRetryable || attempt === RETRY_CONFIG.maxAttempts - 1) {
        throw new ClaudeError(
          `Claude API error: ${error.message}`,
          error.code || error.error?.type || 'UNKNOWN_ERROR',
          isRetryable
        );
      }

      // Calculate delay and retry
      const delay = calculateDelay(attempt, isRateLimit);
      console.warn(
        `[ClaudeClient] Request failed (attempt ${attempt + 1}/${RETRY_CONFIG.maxAttempts}). ` +
          `Retrying in ${delay}ms... Error: ${error.message}`
      );

      await sleep(delay);
    }
  }

  // This should never be reached due to the throw in the loop
  throw new ClaudeError(
    `Failed after ${RETRY_CONFIG.maxAttempts} attempts: ${lastError?.message}`,
    lastError?.code || 'MAX_RETRIES_EXCEEDED',
    false
  );
}

/**
 * Generates content with Claude and parses the response as JSON.
 * Automatically extracts JSON from markdown code blocks if present.
 *
 * @param prompt - The prompt to send to Claude
 * @param systemPrompt - Optional system prompt for context
 * @returns Parsed JSON object of type T, or null if Claude is unavailable
 * @throws {ClaudeError} If generation fails or JSON parsing fails
 */
export async function generateJSON<T>(
  prompt: string,
  systemPrompt?: string
): Promise<T | null> {
  const rawResponse = await generateWithClaude(prompt, systemPrompt);

  if (rawResponse === null) {
    // Claude not available - graceful fallback
    return null;
  }

  try {
    // Try to extract JSON from markdown code blocks
    const jsonMatch = rawResponse.match(/```(?:json)?\s*([\s\S]*?)```/);
    const jsonString = jsonMatch ? jsonMatch[1].trim() : rawResponse.trim();

    return JSON.parse(jsonString) as T;
  } catch (error: any) {
    throw new ClaudeError(
      `Failed to parse Claude response as JSON: ${error.message}`,
      'INVALID_JSON',
      false
    );
  }
}

// ============================================================================
// LEARNING PATH PLANNING
// ============================================================================

/**
 * System prompt for learning path planning.
 * Establishes Claude's role as an expert language learning curriculum designer.
 */
const LEARNING_PATH_SYSTEM_PROMPT = `You are an expert language learning curriculum designer with deep knowledge of CEFR standards, spaced repetition, and second language acquisition research.

Your role is to create strategic learning path plans that will be used to generate detailed content. You should:

1. Analyze the user's profile (native language, target language, current level, goals, interests)
2. Design a progression that builds on previous knowledge
3. Create specific briefs for each "stair" (learning unit) with clear constraints
4. Ensure vocabulary and grammar are appropriate for the user's level
5. Include communicative goals that align with user motivations

Always respond with valid JSON matching the LearningPathPlan schema.`;

/**
 * Generates a strategic learning path plan based on user profile.
 * This is the primary function for Claude's supervisor role in the orchestration.
 *
 * Claude analyzes the user profile and creates a strategic plan with briefs
 * for each stair. These briefs are then used by Gemini to generate the actual
 * content (vocabulary, sentences, quizzes, etc.).
 *
 * @param profile - User's learning profile with preferences and level
 * @returns A complete LearningPathPlan, or null if Claude is unavailable
 * @throws {ClaudeError} If generation or validation fails
 */
export async function generateLearningPathPlan(
  profile: UserLearningProfile
): Promise<LearningPathPlan | null> {
  // Check if Claude is available
  if (!isClaudeAvailable()) {
    console.warn(
      '[ClaudeClient] Claude not available for learning path planning. ' +
        'Falling back to Gemini-only mode.'
    );
    return null;
  }

  const prompt = `Create a personalized learning path plan for a language learner with the following profile:

## User Profile
- Native Language: ${profile.nativeLanguage}
- Target Language: ${profile.targetLanguage}
- Current Level: ${profile.currentLevel}
- Learning Goals: ${profile.learningGoals.join(', ')}
- Interests: ${profile.interests.join(', ')}
- Daily Practice Time: ${profile.dailyTimeMinutes} minutes
${profile.motivation ? `- Motivation: ${profile.motivation}` : ''}
${profile.timeline ? `- Timeline: ${profile.timeline}` : ''}

## Requirements
1. Create 6-10 stairs (learning units) appropriate for their level
2. Each stair should focus on a specific theme related to their interests
3. Include vocabulary, grammar patterns, and communicative goals for each stair
4. Set appropriate constraints (word frequency bands, sentence lengths)
5. Ensure smooth progression from current level

## Output Format
Return a JSON object with this structure:
{
  "userId": "string",
  "totalStairs": number,
  "estimatedDuration": "string (e.g., '4 weeks')",
  "stairs": [
    {
      "id": "stair_1",
      "position": 1,
      "theme": "string",
      "cefrLevel": "string (e.g., 'A1')",
      "vocabularyFocus": ["word1", "word2", ...],
      "grammarPatterns": ["pattern1", "pattern2", ...],
      "communicativeGoals": ["goal1", "goal2", ...],
      "constraints": {
        "wordFrequencyBand": [1, 3000],
        "maxSentenceLength": 10,
        "avoidTopics": []
      }
    }
  ],
  "progressionLogic": "Description of how the path builds skills progressively"
}`;

  try {
    const plan = await generateJSON<LearningPathPlan>(
      prompt,
      LEARNING_PATH_SYSTEM_PROMPT
    );

    if (!plan) {
      return null;
    }

    // Add metadata
    plan.metadata = {
      generatedAt: new Date().toISOString(),
      modelVersion: CLAUDE_CONFIG.model,
    };

    // Validate the plan structure
    validateLearningPathPlan(plan);

    return plan;
  } catch (error: any) {
    if (error instanceof ClaudeError) {
      throw error;
    }

    throw new ClaudeError(
      `Learning path plan generation failed: ${error.message}`,
      'PLAN_GENERATION_FAILED',
      false
    );
  }
}

/**
 * Validates that a learning path plan has the required structure.
 * @throws {ClaudeError} If validation fails
 */
function validateLearningPathPlan(plan: LearningPathPlan): void {
  if (!plan.stairs || plan.stairs.length === 0) {
    throw new ClaudeError(
      'Learning path plan must contain at least one stair',
      'INVALID_PLAN_STRUCTURE',
      false
    );
  }

  if (plan.totalStairs !== plan.stairs.length) {
    throw new ClaudeError(
      `totalStairs (${plan.totalStairs}) does not match stairs array length (${plan.stairs.length})`,
      'INVALID_PLAN_STRUCTURE',
      false
    );
  }

  // Validate each stair has required fields
  for (const stair of plan.stairs) {
    if (!stair.id || !stair.theme || !stair.cefrLevel) {
      throw new ClaudeError(
        `Stair at position ${stair.position} is missing required fields`,
        'INVALID_STAIR_STRUCTURE',
        false
      );
    }

    if (
      !Array.isArray(stair.vocabularyFocus) ||
      !Array.isArray(stair.grammarPatterns) ||
      !Array.isArray(stair.communicativeGoals)
    ) {
      throw new ClaudeError(
        `Stair "${stair.id}" has invalid array fields`,
        'INVALID_STAIR_STRUCTURE',
        false
      );
    }
  }
}

// ============================================================================
// EXPORTS
// ============================================================================

export {
  CLAUDE_CONFIG,
  RETRY_CONFIG,
  getClient,
};
